// <auto-generated />
using HRMS.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRMS.Migrations
{
    [DbContext(typeof(HRMSDbContext))]
    [Migration("20260730101500_HrmsFullSchema")]
    public partial class HrmsFullSchema
    {
    }
}
