using Microsoft.EntityFrameworkCore;

namespace HRMS.Data;

public static class LeaveWorkflowSchemaBootstrap
{
    public static async Task EnsureAsync(HRMSDbContext db, CancellationToken cancellationToken = default)
    {
        const string sql = """
            ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS approval_remarks character varying(512);
            ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS approved_at timestamp with time zone;
            ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS approved_by_user_id integer;
            ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS attachment_file_name character varying(256);
            ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS attachment_path character varying(512);
            ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_leave_requests_users_approved_by_user_id'
                ) THEN
                    ALTER TABLE leave_requests
                        ADD CONSTRAINT "FK_leave_requests_users_approved_by_user_id"
                        FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL;
                END IF;
            END $$;

            CREATE INDEX IF NOT EXISTS "IX_leave_requests_approved_by_user_id" ON leave_requests (approved_by_user_id);

            CREATE TABLE IF NOT EXISTS leave_notifications (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_id integer NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
                leave_request_id integer NULL REFERENCES leave_requests(id) ON DELETE SET NULL,
                title character varying(128) NOT NULL,
                message character varying(512) NOT NULL,
                is_read boolean NOT NULL DEFAULT FALSE,
                created_at timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
            );

            CREATE INDEX IF NOT EXISTS "IX_leave_notifications_employee_id" ON leave_notifications (employee_id);
            CREATE INDEX IF NOT EXISTS "IX_leave_notifications_is_read" ON leave_notifications (is_read);
            CREATE INDEX IF NOT EXISTS "IX_leave_notifications_leave_request_id" ON leave_notifications (leave_request_id);

            CREATE TABLE IF NOT EXISTS leave_rejection_reasons (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title character varying(128) NOT NULL,
                is_active boolean NOT NULL DEFAULT TRUE,
                sort_order integer NOT NULL DEFAULT 0
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_leave_rejection_reasons_title" ON leave_rejection_reasons (title);

            INSERT INTO leave_rejection_reasons (id, title, is_active, sort_order)
            SELECT v.id, v.title, TRUE, v.sort_order
            FROM (VALUES
                (1, 'Project Delivery Deadline / Critical Milestone', 1),
                (2, 'Insufficient Leave Balance', 2),
                (3, 'Team Resource Shortage on Requested Dates', 3),
                (4, 'Overlapping Team Member Leave', 4),
                (5, 'Incomplete Information / Missing Attachments', 5),
                (6, 'Other Reason', 6)
            ) AS v(id, title, sort_order)
            WHERE NOT EXISTS (SELECT 1 FROM leave_rejection_reasons LIMIT 1);

            SELECT setval(
                pg_get_serial_sequence('leave_rejection_reasons', 'id'),
                GREATEST((SELECT COALESCE(MAX(id), 1) FROM leave_rejection_reasons), 1)
            );
            """;

        await db.Database.ExecuteSqlRawAsync(sql, cancellationToken);
    }
}
