using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260830000000_AddProcurementPhase8PurchaseBills")]
    public partial class AddProcurementPhase8PurchaseBills : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    -- 1. Document Sequence
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_bill_document_sequences'
    ) THEN
        CREATE TABLE purchase_bill_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Prefix" character varying(64) NOT NULL,
            "LastSequence" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_purchase_bill_document_sequences_Prefix" ON purchase_bill_document_sequences ("Prefix");
    END IF;

    -- 2. Purchase Bills
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_bills'
    ) THEN
        CREATE TABLE purchase_bills (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "BillNumber" character varying(64) NOT NULL,
            "InvoiceNumber" character varying(128) NOT NULL,
            "VendorId" integer NOT NULL DEFAULT 0,
            "VendorName" character varying(256) NOT NULL,
            "PurchaseOrderId" integer NULL,
            "PurchaseOrderNumber" character varying(64) NULL,
            "GRNId" integer NULL,
            "GRNNumber" character varying(64) NULL,
            "InvoiceDate" timestamp with time zone NOT NULL DEFAULT NOW(),
            "DueDate" timestamp with time zone NOT NULL DEFAULT NOW(),
            "Currency" character varying(16) NOT NULL DEFAULT 'INR',
            "SubTotal" numeric(18,4) NOT NULL DEFAULT 0,
            "DiscountTotal" numeric(18,4) NOT NULL DEFAULT 0,
            "TaxTotal" numeric(18,4) NOT NULL DEFAULT 0,
            "RoundOff" numeric(18,4) NOT NULL DEFAULT 0,
            "GrandTotal" numeric(18,4) NOT NULL DEFAULT 0,
            "PaidAmount" numeric(18,4) NOT NULL DEFAULT 0,
            "BalanceAmount" numeric(18,4) NOT NULL DEFAULT 0,
            "PaymentTerms" character varying(128) NOT NULL DEFAULT 'Net 30 Days',
            "PaymentStatus" character varying(64) NOT NULL DEFAULT 'Unpaid',
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "AttachmentsCount" integer NOT NULL DEFAULT 0,
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_purchase_bills_BillNumber" ON purchase_bills ("BillNumber");
        CREATE INDEX "IX_purchase_bills_Status" ON purchase_bills ("Status");
        CREATE INDEX "IX_purchase_bills_PaymentStatus" ON purchase_bills ("PaymentStatus");
        CREATE INDEX "IX_purchase_bills_GRNId" ON purchase_bills ("GRNId");
        CREATE INDEX "IX_purchase_bills_PurchaseOrderId" ON purchase_bills ("PurchaseOrderId");
    END IF;

    -- 3. Purchase Bill Lines
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_bill_lines'
    ) THEN
        CREATE TABLE purchase_bill_lines (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PurchaseBillId" integer NOT NULL REFERENCES purchase_bills("Id") ON DELETE CASCADE,
            "ItemName" character varying(256) NOT NULL,
            "Description" character varying(500) NOT NULL DEFAULT '',
            "Quantity" numeric(18,4) NOT NULL DEFAULT 0,
            "UnitPrice" numeric(18,4) NOT NULL DEFAULT 0,
            "DiscountAmount" numeric(18,4) NOT NULL DEFAULT 0,
            "TaxPercent" numeric(18,4) NOT NULL DEFAULT 18,
            "TaxAmount" numeric(18,4) NOT NULL DEFAULT 0,
            "TotalAmount" numeric(18,4) NOT NULL DEFAULT 0
        );

        CREATE INDEX "IX_purchase_bill_lines_PurchaseBillId" ON purchase_bill_lines ("PurchaseBillId");
    END IF;

    -- 4. Purchase Bill Histories
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_bill_histories'
    ) THEN
        CREATE TABLE purchase_bill_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PurchaseBillId" integer NOT NULL REFERENCES purchase_bills("Id") ON DELETE CASCADE,
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "Date" timestamp with time zone NOT NULL DEFAULT NOW(),
            "User" character varying(256) NOT NULL DEFAULT '',
            "Remarks" character varying(2000) NOT NULL DEFAULT ''
        );

        CREATE INDEX "IX_purchase_bill_histories_PurchaseBillId" ON purchase_bill_histories ("PurchaseBillId");
    END IF;

END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "purchase_bill_histories");
            migrationBuilder.DropTable(name: "purchase_bill_lines");
            migrationBuilder.DropTable(name: "purchase_bills");
            migrationBuilder.DropTable(name: "purchase_bill_document_sequences");
        }
    }
}
