using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260922200000_HardenFinancialSettlementAndLedgerSchema")]
    public partial class HardenFinancialSettlementAndLedgerSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    -- 1. Add GST, TDS, and Posting columns to purchase_bills
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'purchase_bills') THEN
                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'purchase_bills' AND (column_name = 'TdsSection' OR column_name = 'tds_section')) THEN
                            ALTER TABLE purchase_bills ADD COLUMN "TdsSection" character varying(32) NULL;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'purchase_bills' AND (column_name = 'TdsPercentage' OR column_name = 'tds_percentage')) THEN
                            ALTER TABLE purchase_bills ADD COLUMN "TdsPercentage" numeric(5,2) NOT NULL DEFAULT 0.00;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'purchase_bills' AND (column_name = 'TdsAmount' OR column_name = 'tds_amount')) THEN
                            ALTER TABLE purchase_bills ADD COLUMN "TdsAmount" numeric(18,4) NOT NULL DEFAULT 0.0000;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'purchase_bills' AND (column_name = 'CgstAmount' OR column_name = 'cgst_amount')) THEN
                            ALTER TABLE purchase_bills ADD COLUMN "CgstAmount" numeric(18,4) NOT NULL DEFAULT 0.0000;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'purchase_bills' AND (column_name = 'SgstAmount' OR column_name = 'sgst_amount')) THEN
                            ALTER TABLE purchase_bills ADD COLUMN "SgstAmount" numeric(18,4) NOT NULL DEFAULT 0.0000;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'purchase_bills' AND (column_name = 'IgstAmount' OR column_name = 'igst_amount')) THEN
                            ALTER TABLE purchase_bills ADD COLUMN "IgstAmount" numeric(18,4) NOT NULL DEFAULT 0.0000;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'purchase_bills' AND (column_name = 'VarianceReason' OR column_name = 'variance_reason')) THEN
                            ALTER TABLE purchase_bills ADD COLUMN "VarianceReason" text NULL;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'purchase_bills' AND (column_name = 'PostedAt' OR column_name = 'posted_at')) THEN
                            ALTER TABLE purchase_bills ADD COLUMN "PostedAt" timestamp with time zone NULL;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'purchase_bills' AND (column_name = 'PostedByUserId' OR column_name = 'posted_by_user_id')) THEN
                            ALTER TABLE purchase_bills ADD COLUMN "PostedByUserId" integer NULL;
                        END IF;
                    END IF;

                    -- 2. Create vendor_payments table
                    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'vendor_payments') THEN
                        CREATE TABLE vendor_payments (
                            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "VendorId" integer NOT NULL REFERENCES vendors("Id") ON DELETE RESTRICT,
                            "PaymentNumber" character varying(64) NOT NULL UNIQUE,
                            "PaymentDate" timestamp with time zone NOT NULL,
                            "PaymentMethod" character varying(64) NOT NULL DEFAULT 'NEFT/RTGS',
                            "BankAccountId" integer NULL,
                            "TotalAmount" numeric(18,4) NOT NULL DEFAULT 0.0000,
                            "UnallocatedAmount" numeric(18,4) NOT NULL DEFAULT 0.0000,
                            "ReferenceNumber" character varying(128) NULL,
                            "Status" character varying(32) NOT NULL DEFAULT 'Cleared',
                            "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            "CreatedByUserId" integer NULL
                        );
                    END IF;

                    -- 3. Create vendor_payment_allocations table
                    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'vendor_payment_allocations') THEN
                        CREATE TABLE vendor_payment_allocations (
                            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "VendorPaymentId" integer NOT NULL REFERENCES vendor_payments("Id") ON DELETE CASCADE,
                            "PurchaseBillId" integer NOT NULL REFERENCES purchase_bills("Id") ON DELETE RESTRICT,
                            "AllocatedAmount" numeric(18,4) NOT NULL,
                            "AllocatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                        );
                    END IF;

                    -- 4. Create vendor_ledger_entries table
                    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'vendor_ledger_entries') THEN
                        CREATE TABLE vendor_ledger_entries (
                            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "VendorId" integer NOT NULL REFERENCES vendors("Id") ON DELETE RESTRICT,
                            "PurchaseBillId" integer NULL REFERENCES purchase_bills("Id") ON DELETE SET NULL,
                            "VoucherNumber" character varying(64) NOT NULL,
                            "EntryDate" timestamp with time zone NOT NULL,
                            "EntryType" character varying(32) NOT NULL, -- 'Bill', 'Payment', 'DebitNote', 'CreditNote'
                            "ReferenceId" integer NULL,
                            "ReferenceNumber" character varying(128) NULL,
                            "DebitAmount" numeric(18,4) NOT NULL DEFAULT 0.0000,
                            "CreditAmount" numeric(18,4) NOT NULL DEFAULT 0.0000,
                            "Narration" text NULL,
                            "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            "CreatedByUserId" integer NULL
                        );
                    END IF;

                    -- 5. Create Performance Indexes
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_vendor_ledger_lookup') THEN
                        CREATE INDEX idx_vendor_ledger_lookup ON vendor_ledger_entries ("VendorId", "EntryDate", "Id");
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_payment_alloc_lookup') THEN
                        CREATE INDEX idx_payment_alloc_lookup ON vendor_payment_allocations ("VendorPaymentId", "PurchaseBillId");
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_bill_aging_lookup') THEN
                        CREATE INDEX idx_bill_aging_lookup ON purchase_bills ("IsDeleted", "Status", "PaymentStatus", "DueDate", "VendorId");
                    END IF;

                    -- 6. Create or Replace Server-Side Aging View
                    CREATE OR REPLACE VIEW vw_vendor_aging_analysis AS
                    SELECT 
                        v."Id" AS vendor_id,
                        v."Name" AS vendor_name,
                        COALESCE(SUM(pb."GrandTotal" - pb."PaidAmount"), 0.0) AS total_outstanding,
                        COALESCE(SUM(CASE WHEN (CURRENT_DATE - pb."DueDate"::date) <= 0 THEN (pb."GrandTotal" - pb."PaidAmount") ELSE 0 END), 0.0) AS current_amount,
                        COALESCE(SUM(CASE WHEN (CURRENT_DATE - pb."DueDate"::date) BETWEEN 1 AND 30 THEN (pb."GrandTotal" - pb."PaidAmount") ELSE 0 END), 0.0) AS aging_1_30,
                        COALESCE(SUM(CASE WHEN (CURRENT_DATE - pb."DueDate"::date) BETWEEN 31 AND 60 THEN (pb."GrandTotal" - pb."PaidAmount") ELSE 0 END), 0.0) AS aging_31_60,
                        COALESCE(SUM(CASE WHEN (CURRENT_DATE - pb."DueDate"::date) BETWEEN 61 AND 90 THEN (pb."GrandTotal" - pb."PaidAmount") ELSE 0 END), 0.0) AS aging_61_90,
                        COALESCE(SUM(CASE WHEN (CURRENT_DATE - pb."DueDate"::date) > 90 THEN (pb."GrandTotal" - pb."PaidAmount") ELSE 0 END), 0.0) AS aging_90_plus
                    FROM vendors v
                    JOIN purchase_bills pb ON pb."VendorId" = v."Id" AND pb."IsDeleted" = false AND pb."Status" = 'Posted' AND pb."PaymentStatus" != 'Paid'
                    GROUP BY v."Id", v."Name";

                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
