using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260922120000_HardenExecutionAndApprovalSchema")]
    public partial class HardenExecutionAndApprovalSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    -- 1. Add FK columns to purchase_order_lines
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'purchase_order_lines') THEN
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'purchase_order_lines' AND (column_name = 'ItemId' OR column_name = 'item_id')
                        ) THEN
                            ALTER TABLE purchase_order_lines ADD COLUMN "ItemId" integer NULL;
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'purchase_order_lines' AND (column_name = 'UomId' OR column_name = 'uom_id')
                        ) THEN
                            ALTER TABLE purchase_order_lines ADD COLUMN "UomId" integer NULL;
                        END IF;
                    END IF;

                    -- 2. Add WarehouseId / warehouse_id to goods_receipts
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'goods_receipts') THEN
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'goods_receipts' AND (column_name = 'WarehouseId' OR column_name = 'warehouse_id')
                        ) THEN
                            ALTER TABLE goods_receipts ADD COLUMN "WarehouseId" integer NULL;
                        END IF;
                    END IF;

                    -- 3. Add RejectionReasonCode & ItemId to goods_receipt_items
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'goods_receipt_items') THEN
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'goods_receipt_items' AND (column_name = 'RejectionReasonCode' OR column_name = 'rejection_reason_code')
                        ) THEN
                            ALTER TABLE goods_receipt_items ADD COLUMN "RejectionReasonCode" text NOT NULL DEFAULT '';
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'goods_receipt_items' AND (column_name = 'ItemId' OR column_name = 'item_id')
                        ) THEN
                            ALTER TABLE goods_receipt_items ADD COLUMN "ItemId" integer NULL;
                        END IF;
                    END IF;

                    -- 4. Create approval_rules and approval_rule_tiers tables & seed defaults
                    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'approval_rules') THEN
                        CREATE TABLE approval_rules (
                            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "Name" character varying(256) NOT NULL,
                            "DocumentType" character varying(64) NOT NULL DEFAULT 'PurchaseOrder',
                            "IsActive" boolean NOT NULL DEFAULT true
                        );

                        INSERT INTO approval_rules ("Id", "Name", "DocumentType", "IsActive")
                        VALUES (1, 'Standard Purchase Order Approval Matrix', 'PurchaseOrder', true);
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'approval_rule_tiers') THEN
                        CREATE TABLE approval_rule_tiers (
                            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "ApprovalRuleId" integer NOT NULL REFERENCES approval_rules("Id") ON DELETE CASCADE,
                            "SequenceNumber" integer NOT NULL,
                            "RequiredRole" character varying(128) NOT NULL,
                            "MinAmount" numeric(18,2) NOT NULL DEFAULT 0.00,
                            "MaxAmount" numeric(18,2) NOT NULL DEFAULT 0.00
                        );

                        INSERT INTO approval_rule_tiers ("ApprovalRuleId", "SequenceNumber", "RequiredRole", "MinAmount", "MaxAmount")
                        VALUES 
                            (1, 1, 'Procurement Manager', 0.00, 10000.00),
                            (1, 2, 'Finance Director', 10000.01, 50000.00),
                            (1, 3, 'CFO', 50000.01, 999999999.00);
                    END IF;

                    -- 5. Create composite performance indexes
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'purchase_orders') THEN
                        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_po_execution') THEN
                            CREATE INDEX idx_po_execution ON purchase_orders ("IsDeleted", "Status", "VendorId", "OrderDate");
                        END IF;
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'goods_receipts') THEN
                        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_grn_execution') THEN
                            CREATE INDEX idx_grn_execution ON goods_receipts ("IsDeleted", "Status", "PurchaseOrderId", "ReceiptDate");
                        END IF;
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'goods_receipt_items') THEN
                        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_grn_items_line') THEN
                            CREATE INDEX idx_grn_items_line ON goods_receipt_items ("GoodsReceiptId", "PurchaseOrderLineId");
                        END IF;
                    END IF;

                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
