using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddProcurementPhase2PRAndRFQ : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    -- 1. Purchase Requisition Sequences
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_requisition_document_sequences'
    ) THEN
        CREATE TABLE purchase_requisition_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Prefix" character varying(64) NOT NULL,
            "LastSequence" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_purchase_requisition_document_sequences_Prefix" ON purchase_requisition_document_sequences ("Prefix");
    END IF;

    -- 2. RFQ Sequences
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'rfq_document_sequences'
    ) THEN
        CREATE TABLE rfq_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Prefix" character varying(64) NOT NULL,
            "LastSequence" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_rfq_document_sequences_Prefix" ON rfq_document_sequences ("Prefix");
    END IF;

    -- 3. Purchase Requisitions Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_requisitions'
    ) THEN
        CREATE TABLE purchase_requisitions (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PRNumber" character varying(64) NOT NULL,
            "Department" character varying(128) NOT NULL,
            "Requestor" character varying(128) NOT NULL,
            "RequiredDate" timestamp with time zone NOT NULL,
            "Priority" character varying(64) NOT NULL DEFAULT 'Normal',
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "InternalNotes" character varying(2000) NOT NULL DEFAULT '',
            "TotalEstimatedAmount" numeric(18,4) NOT NULL DEFAULT 0,
            "RFQId" integer NULL,
            "RFQNumber" character varying(64) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_purchase_requisitions_PRNumber" ON purchase_requisitions ("PRNumber");
        CREATE INDEX "IX_purchase_requisitions_Department" ON purchase_requisitions ("Department");
        CREATE INDEX "IX_purchase_requisitions_Status" ON purchase_requisitions ("Status");
        CREATE INDEX "IX_purchase_requisitions_Priority" ON purchase_requisitions ("Priority");
    END IF;

    -- 4. Purchase Requisition Lines Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_requisition_lines'
    ) THEN
        CREATE TABLE purchase_requisition_lines (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PurchaseRequisitionId" integer NOT NULL REFERENCES purchase_requisitions("Id") ON DELETE CASCADE,
            "ItemName" character varying(256) NOT NULL,
            "Description" character varying(1000) NOT NULL DEFAULT '',
            "Quantity" numeric(18,4) NOT NULL,
            "Uom" character varying(64) NOT NULL DEFAULT 'PCS',
            "EstimatedPrice" numeric(18,4) NOT NULL DEFAULT 0,
            "TotalAmount" numeric(18,4) NOT NULL DEFAULT 0
        );

        CREATE INDEX "IX_purchase_requisition_lines_PurchaseRequisitionId" ON purchase_requisition_lines ("PurchaseRequisitionId");
    END IF;

    -- 5. Purchase Requisition Status Histories Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_requisition_status_histories'
    ) THEN
        CREATE TABLE purchase_requisition_status_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PurchaseRequisitionId" integer NOT NULL REFERENCES purchase_requisitions("Id") ON DELETE CASCADE,
            "Status" character varying(64) NOT NULL,
            "PreviousStatus" character varying(64) NULL,
            "User" character varying(256) NOT NULL DEFAULT '',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Date" timestamp with time zone NOT NULL DEFAULT NOW()
        );

        CREATE INDEX "IX_purchase_requisition_status_histories_PurchaseRequisitionId_Date" ON purchase_requisition_status_histories ("PurchaseRequisitionId", "Date");
    END IF;

    -- 6. Request for Quotations Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'request_for_quotations'
    ) THEN
        CREATE TABLE request_for_quotations (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "RFQNumber" character varying(64) NOT NULL,
            "RFQDate" timestamp with time zone NOT NULL,
            "DueDate" timestamp with time zone NOT NULL,
            "PurchaseRequisitionId" integer NULL REFERENCES purchase_requisitions("Id") ON DELETE SET NULL,
            "PurchaseRequisitionNumber" character varying(64) NOT NULL DEFAULT '',
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "DeliveryTerms" character varying(1000) NOT NULL DEFAULT '',
            "PaymentTerms" character varying(1000) NOT NULL DEFAULT '',
            "VendorNotes" character varying(2000) NOT NULL DEFAULT '',
            "ComparisonId" integer NULL,
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_request_for_quotations_RFQNumber" ON request_for_quotations ("RFQNumber");
        CREATE INDEX "IX_request_for_quotations_Status" ON request_for_quotations ("Status");
        CREATE INDEX "IX_request_for_quotations_PurchaseRequisitionId" ON request_for_quotations ("PurchaseRequisitionId");
    END IF;

    -- Add Foreign Key from PR to RFQ
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'FK_purchase_requisitions_request_for_quotations_RFQId'
    ) THEN
        ALTER TABLE purchase_requisitions
        ADD CONSTRAINT "FK_purchase_requisitions_request_for_quotations_RFQId"
        FOREIGN KEY ("RFQId") REFERENCES request_for_quotations("Id") ON DELETE SET NULL;
    END IF;

    -- 7. RFQ Lines Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'rfq_lines'
    ) THEN
        CREATE TABLE rfq_lines (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "RequestForQuotationId" integer NOT NULL REFERENCES request_for_quotations("Id") ON DELETE CASCADE,
            "ItemName" character varying(256) NOT NULL,
            "Description" character varying(1000) NOT NULL DEFAULT '',
            "Quantity" numeric(18,4) NOT NULL,
            "Uom" character varying(64) NOT NULL DEFAULT 'PCS',
            "TargetUnitPrice" numeric(18,4) NULL
        );

        CREATE INDEX "IX_rfq_lines_RequestForQuotationId" ON rfq_lines ("RequestForQuotationId");
    END IF;

    -- 8. RFQ Vendors Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'rfq_vendors'
    ) THEN
        CREATE TABLE rfq_vendors (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "RequestForQuotationId" integer NOT NULL REFERENCES request_for_quotations("Id") ON DELETE CASCADE,
            "VendorId" integer NOT NULL REFERENCES vendors("Id") ON DELETE RESTRICT,
            "VendorName" character varying(256) NOT NULL DEFAULT '',
            "ContactEmail" character varying(256) NOT NULL DEFAULT '',
            "ContactPhone" character varying(64) NOT NULL DEFAULT '',
            "Status" character varying(64) NOT NULL DEFAULT 'Pending',
            "RespondedDate" timestamp with time zone NULL
        );

        CREATE INDEX "IX_rfq_vendors_RequestForQuotationId" ON rfq_vendors ("RequestForQuotationId");
        CREATE INDEX "IX_rfq_vendors_VendorId" ON rfq_vendors ("VendorId");
    END IF;

    -- 9. RFQ Status Histories Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'rfq_status_histories'
    ) THEN
        CREATE TABLE rfq_status_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "RequestForQuotationId" integer NOT NULL REFERENCES request_for_quotations("Id") ON DELETE CASCADE,
            "Status" character varying(64) NOT NULL,
            "PreviousStatus" character varying(64) NULL,
            "User" character varying(256) NOT NULL DEFAULT '',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Date" timestamp with time zone NOT NULL DEFAULT NOW()
        );

        CREATE INDEX "IX_rfq_status_histories_RequestForQuotationId_Date" ON rfq_status_histories ("RequestForQuotationId", "Date");
    END IF;

END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "rfq_status_histories");
            migrationBuilder.DropTable(name: "rfq_vendors");
            migrationBuilder.DropTable(name: "rfq_lines");
            migrationBuilder.DropTable(name: "purchase_requisition_status_histories");
            migrationBuilder.DropTable(name: "purchase_requisition_lines");
            migrationBuilder.DropTable(name: "request_for_quotations");
            migrationBuilder.DropTable(name: "purchase_requisitions");
            migrationBuilder.DropTable(name: "rfq_document_sequences");
            migrationBuilder.DropTable(name: "purchase_requisition_document_sequences");
        }
    }
}
