using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddProformaInvoices : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'proforma_invoice_document_sequences'
    ) THEN
        CREATE TABLE proforma_invoice_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Year" integer NOT NULL,
            "LastSequence" integer NOT NULL
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_proforma_invoice_document_sequences_Year'
    ) THEN
        CREATE UNIQUE INDEX "IX_proforma_invoice_document_sequences_Year"
            ON proforma_invoice_document_sequences ("Year");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'proforma_invoices'
    ) THEN
        CREATE TABLE proforma_invoices (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PiNumber" character varying(64) NOT NULL,
            "InvoiceDate" date NOT NULL,
            "ValidUntil" date NOT NULL,
            "CustomerId" character varying(64) NOT NULL,
            "CustomerName" character varying(256) NOT NULL,
            "ContactPerson" character varying(256) NOT NULL,
            "BillingAddress" character varying(2000) NOT NULL,
            "ShippingAddress" character varying(2000) NOT NULL,
            "SalesPersonUserId" integer NOT NULL,
            "SalesPerson" character varying(256) NOT NULL,
            "Currency" character varying(8) NOT NULL,
            "ExchangeRate" numeric(18,6) NOT NULL,
            "QuotationId" integer NULL,
            "QuotationNumber" character varying(64) NOT NULL,
            "SalesOrderId" integer NULL,
            "SalesOrderNumber" character varying(64) NOT NULL,
            "PaymentTerms" character varying(128) NOT NULL,
            "DeliveryTerms" character varying(128) NOT NULL,
            "CustomerNotes" character varying(4000) NOT NULL,
            "InternalNotes" character varying(4000) NOT NULL,
            "Subtotal" numeric(18,2) NOT NULL,
            "DiscountTotal" numeric(18,2) NOT NULL,
            "TaxTotal" numeric(18,2) NOT NULL,
            "GrandTotal" numeric(18,2) NOT NULL,
            "Status" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL,
            "CreatedBy" character varying(64) NOT NULL,
            "CreatedDate" timestamp with time zone NOT NULL,
            "UpdatedBy" character varying(64) NOT NULL,
            "UpdatedDate" timestamp with time zone NOT NULL,
            "IsDeleted" boolean NOT NULL DEFAULT FALSE,
            "ConvertedInvoiceNumber" character varying(64) NULL,
            "ConvertedOn" timestamp with time zone NULL
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'proforma_invoices' AND constraint_name = 'FK_proforma_invoices_sales_orders_SalesOrderId'
    ) THEN
        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'sales_orders') THEN
            ALTER TABLE proforma_invoices
                ADD CONSTRAINT "FK_proforma_invoices_sales_orders_SalesOrderId"
                FOREIGN KEY ("SalesOrderId") REFERENCES sales_orders ("Id") ON DELETE SET NULL;
        END IF;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_proforma_invoices_PiNumber') THEN
        CREATE UNIQUE INDEX "IX_proforma_invoices_PiNumber" ON proforma_invoices ("PiNumber");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_proforma_invoices_Status') THEN
        CREATE INDEX "IX_proforma_invoices_Status" ON proforma_invoices ("Status");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_proforma_invoices_InvoiceDate') THEN
        CREATE INDEX "IX_proforma_invoices_InvoiceDate" ON proforma_invoices ("InvoiceDate");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_proforma_invoices_CustomerName') THEN
        CREATE INDEX "IX_proforma_invoices_CustomerName" ON proforma_invoices ("CustomerName");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_proforma_invoices_IsDeleted') THEN
        CREATE INDEX "IX_proforma_invoices_IsDeleted" ON proforma_invoices ("IsDeleted");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_proforma_invoices_SalesOrderId') THEN
        CREATE INDEX "IX_proforma_invoices_SalesOrderId" ON proforma_invoices ("SalesOrderId");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'proforma_invoice_items'
    ) THEN
        CREATE TABLE proforma_invoice_items (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProformaInvoiceId" integer NOT NULL,
            "LineKey" character varying(64) NOT NULL,
            "ItemName" character varying(512) NOT NULL,
            "Description" character varying(2000) NOT NULL,
            "Quantity" numeric(18,4) NOT NULL,
            "Unit" character varying(32) NOT NULL,
            "Rate" numeric(18,4) NOT NULL,
            "Discount" numeric(9,4) NOT NULL,
            "Gst" numeric(9,4) NOT NULL,
            "TaxAmount" numeric(18,2) NOT NULL,
            "Amount" numeric(18,2) NOT NULL,
            "SortOrder" integer NOT NULL,
            CONSTRAINT "FK_proforma_invoice_items_proforma_invoices_ProformaInvoiceId"
                FOREIGN KEY ("ProformaInvoiceId") REFERENCES proforma_invoices ("Id") ON DELETE CASCADE
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_proforma_invoice_items_ProformaInvoiceId_SortOrder') THEN
        CREATE INDEX "IX_proforma_invoice_items_ProformaInvoiceId_SortOrder"
            ON proforma_invoice_items ("ProformaInvoiceId", "SortOrder");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'proforma_invoice_status_histories'
    ) THEN
        CREATE TABLE proforma_invoice_status_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProformaInvoiceId" integer NOT NULL,
            "EntryKey" character varying(64) NOT NULL,
            "OldStatus" character varying(64) NULL,
            "NewStatus" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL,
            "ChangedBy" character varying(64) NOT NULL,
            "ChangedOn" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_proforma_invoice_status_histories_proforma_invoices_ProformaInvoiceId"
                FOREIGN KEY ("ProformaInvoiceId") REFERENCES proforma_invoices ("Id") ON DELETE CASCADE
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_proforma_invoice_status_histories_ProformaInvoiceId_ChangedOn') THEN
        CREATE INDEX "IX_proforma_invoice_status_histories_ProformaInvoiceId_ChangedOn"
            ON proforma_invoice_status_histories ("ProformaInvoiceId", "ChangedOn");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'proforma_invoice_approval_histories'
    ) THEN
        CREATE TABLE proforma_invoice_approval_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProformaInvoiceId" integer NOT NULL,
            "EntryKey" character varying(64) NOT NULL,
            "ApprovalLevel" character varying(64) NOT NULL,
            "Decision" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL,
            "ApprovedBy" character varying(64) NOT NULL,
            "ApprovedOn" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_proforma_invoice_approval_histories_proforma_invoices_ProformaInvoiceId"
                FOREIGN KEY ("ProformaInvoiceId") REFERENCES proforma_invoices ("Id") ON DELETE CASCADE
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_proforma_invoice_approval_histories_ProformaInvoiceId_ApprovedOn') THEN
        CREATE INDEX "IX_proforma_invoice_approval_histories_ProformaInvoiceId_ApprovedOn"
            ON proforma_invoice_approval_histories ("ProformaInvoiceId", "ApprovedOn");
    END IF;
END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP TABLE IF EXISTS proforma_invoice_approval_histories;
DROP TABLE IF EXISTS proforma_invoice_status_histories;
DROP TABLE IF EXISTS proforma_invoice_items;
DROP TABLE IF EXISTS proforma_invoices;
DROP TABLE IF EXISTS proforma_invoice_document_sequences;
""");
        }
    }
}
