using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddAdvancePayments : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'advance_payment_document_sequences'
    ) THEN
        CREATE TABLE advance_payment_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "FinancialYear" integer NOT NULL,
            "Prefix" character varying(16) NOT NULL,
            "LastNumber" integer NOT NULL,
            "CreatedOn" timestamp with time zone NOT NULL
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public'
          AND indexname = 'IX_advance_payment_document_sequences_FinancialYear_Prefix'
    ) THEN
        CREATE UNIQUE INDEX "IX_advance_payment_document_sequences_FinancialYear_Prefix"
            ON advance_payment_document_sequences ("FinancialYear", "Prefix");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'advance_payments'
    ) THEN
        CREATE TABLE advance_payments (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PaymentNumber" character varying(64) NOT NULL,
            "CustomerId" character varying(64) NOT NULL,
            "CustomerName" character varying(256) NOT NULL,
            "SalesOrderId" integer NULL,
            "SalesOrderNumber" character varying(64) NOT NULL,
            "QuotationId" integer NULL,
            "QuotationNumber" character varying(64) NOT NULL,
            "PaymentDate" date NOT NULL,
            "PaymentMode" character varying(64) NOT NULL,
            "ReferenceNumber" character varying(128) NOT NULL,
            "Currency" character varying(8) NOT NULL,
            "ExchangeRate" numeric(18,6) NOT NULL,
            "AdvanceAmount" numeric(18,2) NOT NULL,
            "AppliedAmount" numeric(18,2) NOT NULL,
            "RemainingAmount" numeric(18,2) NOT NULL,
            "Status" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL,
            "AttachmentName" character varying(512) NULL,
            "VerifiedBy" character varying(64) NULL,
            "VerifiedOn" timestamp with time zone NULL,
            "ReceivedBy" character varying(64) NULL,
            "ReceivedOn" timestamp with time zone NULL,
            "CreatedBy" character varying(64) NOT NULL,
            "CreatedDate" timestamp with time zone NOT NULL,
            "UpdatedBy" character varying(64) NOT NULL,
            "UpdatedDate" timestamp with time zone NOT NULL,
            "IsDeleted" boolean NOT NULL DEFAULT FALSE
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'advance_payments'
          AND constraint_name = 'FK_advance_payments_sales_orders_SalesOrderId'
    ) THEN
        IF EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = 'sales_orders'
        ) THEN
            ALTER TABLE advance_payments
                ADD CONSTRAINT "FK_advance_payments_sales_orders_SalesOrderId"
                FOREIGN KEY ("SalesOrderId") REFERENCES sales_orders ("Id") ON DELETE SET NULL;
        END IF;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_advance_payments_PaymentNumber') THEN
        CREATE UNIQUE INDEX "IX_advance_payments_PaymentNumber" ON advance_payments ("PaymentNumber");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_advance_payments_Status') THEN
        CREATE INDEX "IX_advance_payments_Status" ON advance_payments ("Status");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_advance_payments_PaymentDate') THEN
        CREATE INDEX "IX_advance_payments_PaymentDate" ON advance_payments ("PaymentDate");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_advance_payments_CustomerName') THEN
        CREATE INDEX "IX_advance_payments_CustomerName" ON advance_payments ("CustomerName");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_advance_payments_IsDeleted') THEN
        CREATE INDEX "IX_advance_payments_IsDeleted" ON advance_payments ("IsDeleted");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_advance_payments_SalesOrderId') THEN
        CREATE INDEX "IX_advance_payments_SalesOrderId" ON advance_payments ("SalesOrderId");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'advance_payment_applications'
    ) THEN
        CREATE TABLE advance_payment_applications (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "AdvancePaymentId" integer NOT NULL,
            "SalesOrderId" integer NOT NULL,
            "SalesOrderNumber" character varying(64) NOT NULL,
            "ApplyAmount" numeric(18,2) NOT NULL,
            "Remarks" character varying(2000) NOT NULL,
            "AppliedBy" character varying(64) NOT NULL,
            "AppliedOn" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_advance_payment_applications_advance_payments_AdvancePaymentId"
                FOREIGN KEY ("AdvancePaymentId") REFERENCES advance_payments ("Id") ON DELETE CASCADE
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE indexname = 'IX_advance_payment_applications_AdvancePaymentId_SalesOrderId'
    ) THEN
        CREATE UNIQUE INDEX "IX_advance_payment_applications_AdvancePaymentId_SalesOrderId"
            ON advance_payment_applications ("AdvancePaymentId", "SalesOrderId");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_advance_payment_applications_SalesOrderId') THEN
        CREATE INDEX "IX_advance_payment_applications_SalesOrderId"
            ON advance_payment_applications ("SalesOrderId");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_advance_payment_applications_AppliedOn') THEN
        CREATE INDEX "IX_advance_payment_applications_AppliedOn"
            ON advance_payment_applications ("AppliedOn");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'advance_payment_timeline'
    ) THEN
        CREATE TABLE advance_payment_timeline (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "AdvancePaymentId" integer NOT NULL,
            "Action" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL,
            "PerformedBy" character varying(64) NOT NULL,
            "PerformedOn" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_advance_payment_timeline_advance_payments_AdvancePaymentId"
                FOREIGN KEY ("AdvancePaymentId") REFERENCES advance_payments ("Id") ON DELETE CASCADE
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE indexname = 'IX_advance_payment_timeline_AdvancePaymentId_PerformedOn'
    ) THEN
        CREATE INDEX "IX_advance_payment_timeline_AdvancePaymentId_PerformedOn"
            ON advance_payment_timeline ("AdvancePaymentId", "PerformedOn");
    END IF;
END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP TABLE IF EXISTS advance_payment_timeline;
DROP TABLE IF EXISTS advance_payment_applications;
DROP TABLE IF EXISTS advance_payments;
DROP TABLE IF EXISTS advance_payment_document_sequences;
""");
        }
    }
}
