using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddPriceLists : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'price_list_document_sequences'
    ) THEN
        CREATE TABLE price_list_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "FinancialYear" integer NOT NULL,
            "Prefix" character varying(16) NOT NULL,
            "LastNumber" integer NOT NULL,
            "CreatedOn" timestamp with time zone NOT NULL
        );
    END IF;

    ALTER TABLE price_list_document_sequences ADD COLUMN IF NOT EXISTS "FinancialYear" integer NOT NULL DEFAULT 0;
    ALTER TABLE price_list_document_sequences ADD COLUMN IF NOT EXISTS "Prefix" character varying(16) NOT NULL DEFAULT 'PL';
    ALTER TABLE price_list_document_sequences ADD COLUMN IF NOT EXISTS "LastNumber" integer NOT NULL DEFAULT 0;
    ALTER TABLE price_list_document_sequences ADD COLUMN IF NOT EXISTS "CreatedOn" timestamp with time zone NOT NULL DEFAULT NOW();

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public'
          AND indexname = 'IX_price_list_document_sequences_FinancialYear_Prefix'
    ) THEN
        CREATE UNIQUE INDEX "IX_price_list_document_sequences_FinancialYear_Prefix"
            ON price_list_document_sequences ("FinancialYear", "Prefix");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'price_lists'
    ) THEN
        CREATE TABLE price_lists (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PriceListNumber" character varying(64) NOT NULL,
            "PriceListName" character varying(256) NOT NULL,
            "Description" character varying(2000) NOT NULL DEFAULT '',
            "CustomerCategory" character varying(64) NOT NULL,
            "Currency" character varying(8) NOT NULL,
            "EffectiveFrom" date NOT NULL,
            "EffectiveTo" date NULL,
            "Status" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "CreatedBy" character varying(64) NOT NULL DEFAULT '',
            "CreatedDate" timestamp with time zone NOT NULL,
            "UpdatedBy" character varying(64) NOT NULL DEFAULT '',
            "UpdatedDate" timestamp with time zone NOT NULL,
            "IsDeleted" boolean NOT NULL DEFAULT FALSE
        );
    END IF;

    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "PriceListNumber" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "PriceListName" character varying(256) NOT NULL DEFAULT '';
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "Description" character varying(2000) NOT NULL DEFAULT '';
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "CustomerCategory" character varying(64) NOT NULL DEFAULT 'Standard';
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "Currency" character varying(8) NOT NULL DEFAULT 'INR';
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "EffectiveFrom" date NOT NULL DEFAULT CURRENT_DATE;
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "EffectiveTo" date NULL;
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "Status" character varying(64) NOT NULL DEFAULT 'Draft';
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "Remarks" character varying(2000) NOT NULL DEFAULT '';
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "CreatedBy" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "CreatedDate" timestamp with time zone NOT NULL DEFAULT NOW();
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "UpdatedBy" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "UpdatedDate" timestamp with time zone NOT NULL DEFAULT NOW();
    ALTER TABLE price_lists ADD COLUMN IF NOT EXISTS "IsDeleted" boolean NOT NULL DEFAULT FALSE;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_price_lists_PriceListNumber') THEN
        CREATE UNIQUE INDEX "IX_price_lists_PriceListNumber" ON price_lists ("PriceListNumber");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_price_lists_Status') THEN
        CREATE INDEX "IX_price_lists_Status" ON price_lists ("Status");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_price_lists_CustomerCategory') THEN
        CREATE INDEX "IX_price_lists_CustomerCategory" ON price_lists ("CustomerCategory");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_price_lists_Currency') THEN
        CREATE INDEX "IX_price_lists_Currency" ON price_lists ("Currency");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_price_lists_EffectiveFrom') THEN
        CREATE INDEX "IX_price_lists_EffectiveFrom" ON price_lists ("EffectiveFrom");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_price_lists_IsDeleted') THEN
        CREATE INDEX "IX_price_lists_IsDeleted" ON price_lists ("IsDeleted");
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE indexname = 'IX_price_lists_PriceListName_CustomerCategory_Currency_Status'
    ) THEN
        CREATE INDEX "IX_price_lists_PriceListName_CustomerCategory_Currency_Status"
            ON price_lists ("PriceListName", "CustomerCategory", "Currency", "Status");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'price_list_items'
    ) THEN
        CREATE TABLE price_list_items (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PriceListId" integer NOT NULL,
            "ItemCode" character varying(64) NOT NULL,
            "ItemName" character varying(256) NOT NULL,
            "ItemCategory" character varying(128) NOT NULL DEFAULT '',
            "Unit" character varying(32) NOT NULL DEFAULT 'Nos',
            "BasePrice" numeric(18,2) NOT NULL,
            "SellingPrice" numeric(18,2) NOT NULL,
            "DiscountPercentage" numeric(9,4) NOT NULL DEFAULT 0,
            "MinimumPrice" numeric(18,2) NOT NULL DEFAULT 0,
            "MaximumDiscount" numeric(9,4) NOT NULL DEFAULT 0,
            "TaxPercentage" numeric(9,4) NOT NULL DEFAULT 0,
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "SortOrder" integer NOT NULL DEFAULT 0,
            CONSTRAINT "FK_price_list_items_price_lists_PriceListId"
                FOREIGN KEY ("PriceListId") REFERENCES price_lists ("Id") ON DELETE CASCADE
        );
    END IF;

    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "PriceListId" integer;
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "ItemCode" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "ItemName" character varying(256) NOT NULL DEFAULT '';
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "ItemCategory" character varying(128) NOT NULL DEFAULT '';
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "Unit" character varying(32) NOT NULL DEFAULT 'Nos';
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "BasePrice" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "SellingPrice" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "DiscountPercentage" numeric(9,4) NOT NULL DEFAULT 0;
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "MinimumPrice" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "MaximumDiscount" numeric(9,4) NOT NULL DEFAULT 0;
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "TaxPercentage" numeric(9,4) NOT NULL DEFAULT 0;
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "Remarks" character varying(2000) NOT NULL DEFAULT '';
    ALTER TABLE price_list_items ADD COLUMN IF NOT EXISTS "SortOrder" integer NOT NULL DEFAULT 0;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = 'price_list_items'
          AND constraint_name = 'FK_price_list_items_price_lists_PriceListId'
    ) THEN
        ALTER TABLE price_list_items
            ADD CONSTRAINT "FK_price_list_items_price_lists_PriceListId"
            FOREIGN KEY ("PriceListId") REFERENCES price_lists ("Id") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_price_list_items_ItemCode') THEN
        CREATE INDEX "IX_price_list_items_ItemCode" ON price_list_items ("ItemCode");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_price_list_items_PriceListId_ItemCode') THEN
        CREATE INDEX "IX_price_list_items_PriceListId_ItemCode"
            ON price_list_items ("PriceListId", "ItemCode");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_price_list_items_PriceListId_SortOrder') THEN
        CREATE INDEX "IX_price_list_items_PriceListId_SortOrder"
            ON price_list_items ("PriceListId", "SortOrder");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'price_list_history'
    ) THEN
        CREATE TABLE price_list_history (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PriceListId" integer NOT NULL,
            "Action" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "ChangedBy" character varying(64) NOT NULL DEFAULT '',
            "ChangedOn" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_price_list_history_price_lists_PriceListId"
                FOREIGN KEY ("PriceListId") REFERENCES price_lists ("Id") ON DELETE CASCADE
        );
    END IF;

    ALTER TABLE price_list_history ADD COLUMN IF NOT EXISTS "PriceListId" integer;
    ALTER TABLE price_list_history ADD COLUMN IF NOT EXISTS "Action" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE price_list_history ADD COLUMN IF NOT EXISTS "Remarks" character varying(2000) NOT NULL DEFAULT '';
    ALTER TABLE price_list_history ADD COLUMN IF NOT EXISTS "ChangedBy" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE price_list_history ADD COLUMN IF NOT EXISTS "ChangedOn" timestamp with time zone NOT NULL DEFAULT NOW();

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = 'price_list_history'
          AND constraint_name = 'FK_price_list_history_price_lists_PriceListId'
    ) THEN
        ALTER TABLE price_list_history
            ADD CONSTRAINT "FK_price_list_history_price_lists_PriceListId"
            FOREIGN KEY ("PriceListId") REFERENCES price_lists ("Id") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE indexname = 'IX_price_list_history_PriceListId_ChangedOn'
    ) THEN
        CREATE INDEX "IX_price_list_history_PriceListId_ChangedOn"
            ON price_list_history ("PriceListId", "ChangedOn");
    END IF;
END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP TABLE IF EXISTS price_list_history;
DROP TABLE IF EXISTS price_list_items;
DROP TABLE IF EXISTS price_lists;
DROP TABLE IF EXISTS price_list_document_sequences;
""");
        }
    }
}
