using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260826000000_AddProcurementPhase4PurchaseOrders")]
    public partial class AddProcurementPhase4PurchaseOrders : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    -- 1. Document Sequence
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_order_document_sequences'
    ) THEN
        CREATE TABLE purchase_order_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Prefix" character varying(64) NOT NULL,
            "LastSequence" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_purchase_order_document_sequences_Prefix" ON purchase_order_document_sequences ("Prefix");
    END IF;

    -- 2. Purchase Orders Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_orders'
    ) THEN
        CREATE TABLE purchase_orders (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PurchaseOrderNumber" character varying(64) NOT NULL,
            "ReferenceNumber" character varying(128) NOT NULL DEFAULT '',
            "VendorId" integer NULL REFERENCES vendors("Id") ON DELETE SET NULL,
            "VendorName" character varying(256) NOT NULL,
            "VendorContact" character varying(256) NOT NULL DEFAULT '',
            "BillingAddress" character varying(1000) NOT NULL DEFAULT '',
            "ShippingAddress" character varying(1000) NOT NULL DEFAULT '',
            "VendorEmail" character varying(256) NOT NULL DEFAULT '',
            "VendorPhone" character varying(64) NOT NULL DEFAULT '',
            "GstNumber" character varying(64) NOT NULL DEFAULT '',
            "OrderDate" timestamp with time zone NOT NULL,
            "ExpectedDeliveryDate" timestamp with time zone NULL,
            "PaymentTerms" character varying(500) NOT NULL DEFAULT 'Net 30',
            "DeliveryTerms" character varying(500) NOT NULL DEFAULT 'Door Delivery',
            "BuyerName" character varying(256) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Priority" character varying(64) NOT NULL DEFAULT 'Normal',
            "Currency" character varying(10) NOT NULL DEFAULT 'INR',
            "SourceType" character varying(64) NOT NULL DEFAULT 'Manual',
            "SalesOrderNumber" character varying(64) NOT NULL DEFAULT '',
            "Subtotal" numeric(18,4) NOT NULL DEFAULT 0,
            "DiscountTotal" numeric(18,4) NOT NULL DEFAULT 0,
            "TaxTotal" numeric(18,4) NOT NULL DEFAULT 0,
            "TotalAmount" numeric(18,4) NOT NULL DEFAULT 0,
            "SubmittedDate" timestamp with time zone NULL,
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_purchase_orders_PurchaseOrderNumber" ON purchase_orders ("PurchaseOrderNumber");
        CREATE INDEX "IX_purchase_orders_Status" ON purchase_orders ("Status");
        CREATE INDEX "IX_purchase_orders_Priority" ON purchase_orders ("Priority");
        CREATE INDEX "IX_purchase_orders_VendorId" ON purchase_orders ("VendorId");
    END IF;

    -- 3. Purchase Order Lines Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_order_lines'
    ) THEN
        CREATE TABLE purchase_order_lines (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PurchaseOrderId" integer NOT NULL REFERENCES purchase_orders("Id") ON DELETE CASCADE,
            "ItemName" character varying(256) NOT NULL,
            "Description" character varying(1000) NOT NULL DEFAULT '',
            "Quantity" numeric(18,4) NOT NULL,
            "Unit" character varying(64) NOT NULL DEFAULT 'Nos',
            "Rate" numeric(18,4) NOT NULL DEFAULT 0,
            "Discount" numeric(5,2) NOT NULL DEFAULT 0,
            "Tax" numeric(5,2) NOT NULL DEFAULT 0,
            "Amount" numeric(18,4) NOT NULL DEFAULT 0
        );

        CREATE INDEX "IX_purchase_order_lines_PurchaseOrderId" ON purchase_order_lines ("PurchaseOrderId");
    END IF;

    -- 4. Purchase Order Status Histories Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_order_status_histories'
    ) THEN
        CREATE TABLE purchase_order_status_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PurchaseOrderId" integer NOT NULL REFERENCES purchase_orders("Id") ON DELETE CASCADE,
            "Status" character varying(64) NOT NULL,
            "PreviousStatus" character varying(64) NULL,
            "Date" timestamp with time zone NOT NULL DEFAULT NOW(),
            "User" character varying(256) NOT NULL DEFAULT '',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Label" character varying(256) NOT NULL DEFAULT ''
        );

        CREATE INDEX "IX_purchase_order_status_histories_PurchaseOrderId_Date" ON purchase_order_status_histories ("PurchaseOrderId", "Date");
    END IF;

    -- 5. Purchase Order Approval Histories Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'purchase_order_approval_histories'
    ) THEN
        CREATE TABLE purchase_order_approval_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PurchaseOrderId" integer NOT NULL REFERENCES purchase_orders("Id") ON DELETE CASCADE,
            "EventKind" character varying(64) NOT NULL,
            "Decision" character varying(128) NOT NULL,
            "Approver" character varying(256) NOT NULL DEFAULT '',
            "Role" character varying(128) NOT NULL DEFAULT 'Procurement Manager',
            "DecisionDate" timestamp with time zone NOT NULL DEFAULT NOW(),
            "Remarks" character varying(2000) NOT NULL DEFAULT ''
        );

        CREATE INDEX "IX_purchase_order_approval_histories_PurchaseOrderId_DecisionDate" ON purchase_order_approval_histories ("PurchaseOrderId", "DecisionDate");
    END IF;

END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "purchase_order_approval_histories");
            migrationBuilder.DropTable(name: "purchase_order_status_histories");
            migrationBuilder.DropTable(name: "purchase_order_lines");
            migrationBuilder.DropTable(name: "purchase_orders");
            migrationBuilder.DropTable(name: "purchase_order_document_sequences");
        }
    }
}
