using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260825000000_AddProcurementPhase3QuotationsAndComparisons")]
    public partial class AddProcurementPhase3QuotationsAndComparisons : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    -- 1. Vendor Quotation Document Sequences
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_quotation_document_sequences'
    ) THEN
        CREATE TABLE vendor_quotation_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Prefix" character varying(64) NOT NULL,
            "LastSequence" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_vendor_quotation_document_sequences_Prefix" ON vendor_quotation_document_sequences ("Prefix");
    END IF;

    -- 2. Vendor Comparison Document Sequences
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_comparison_document_sequences'
    ) THEN
        CREATE TABLE vendor_comparison_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Prefix" character varying(64) NOT NULL,
            "LastSequence" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_vendor_comparison_document_sequences_Prefix" ON vendor_comparison_document_sequences ("Prefix");
    END IF;

    -- 3. Vendor Quotations Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_quotations'
    ) THEN
        CREATE TABLE vendor_quotations (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "QuotationNumber" character varying(64) NOT NULL,
            "RequestForQuotationId" integer NULL REFERENCES request_for_quotations("Id") ON DELETE SET NULL,
            "VendorId" integer NOT NULL REFERENCES vendors("Id") ON DELETE RESTRICT,
            "VendorName" character varying(256) NOT NULL,
            "QuotationRef" character varying(128) NOT NULL DEFAULT '',
            "QuotationDate" timestamp with time zone NOT NULL,
            "ValidityDate" timestamp with time zone NULL,
            "DeliveryTimeDays" integer NOT NULL DEFAULT 0,
            "LeadTime" character varying(128) NOT NULL DEFAULT '',
            "WarrantyPeriod" character varying(128) NOT NULL DEFAULT '',
            "PaymentTerms" character varying(500) NOT NULL DEFAULT '',
            "SubTotal" numeric(18,4) NOT NULL DEFAULT 0,
            "DiscountPercent" numeric(5,2) NOT NULL DEFAULT 0,
            "DiscountAmount" numeric(18,4) NOT NULL DEFAULT 0,
            "TaxPercent" numeric(5,2) NOT NULL DEFAULT 0,
            "TaxAmount" numeric(18,4) NOT NULL DEFAULT 0,
            "TotalCost" numeric(18,4) NOT NULL DEFAULT 0,
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_vendor_quotations_QuotationNumber" ON vendor_quotations ("QuotationNumber");
        CREATE INDEX "IX_vendor_quotations_RequestForQuotationId" ON vendor_quotations ("RequestForQuotationId");
        CREATE INDEX "IX_vendor_quotations_VendorId" ON vendor_quotations ("VendorId");
    END IF;

    -- 4. Vendor Quotation Lines Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_quotation_lines'
    ) THEN
        CREATE TABLE vendor_quotation_lines (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VendorQuotationId" integer NOT NULL REFERENCES vendor_quotations("Id") ON DELETE CASCADE,
            "ItemName" character varying(256) NOT NULL,
            "Quantity" numeric(18,4) NOT NULL,
            "Uom" character varying(64) NOT NULL DEFAULT 'PCS',
            "UnitPrice" numeric(18,4) NOT NULL DEFAULT 0,
            "TaxPercent" numeric(5,2) NOT NULL DEFAULT 0,
            "DiscountPercent" numeric(5,2) NOT NULL DEFAULT 0,
            "Amount" numeric(18,4) NOT NULL DEFAULT 0
        );

        CREATE INDEX "IX_vendor_quotation_lines_VendorQuotationId" ON vendor_quotation_lines ("VendorQuotationId");
    END IF;

    -- 5. Vendor Comparisons Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_comparisons'
    ) THEN
        CREATE TABLE vendor_comparisons (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ComparisonNumber" character varying(64) NOT NULL,
            "RFQId" integer NULL REFERENCES request_for_quotations("Id") ON DELETE SET NULL,
            "RFQNumber" character varying(64) NOT NULL DEFAULT '',
            "Title" character varying(256) NOT NULL,
            "ComparisonDate" timestamp with time zone NOT NULL,
            "RecommendationNotes" character varying(2000) NOT NULL DEFAULT '',
            "RecommendedVendorId" integer NOT NULL DEFAULT 0,
            "SelectedWinnerVendorId" integer NULL,
            "SelectedWinnerVendorName" character varying(256) NOT NULL DEFAULT '',
            "PurchaseOrderId" integer NULL,
            "PurchaseOrderNumber" character varying(64) NOT NULL DEFAULT '',
            "Status" character varying(64) NOT NULL DEFAULT 'Pending',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_vendor_comparisons_ComparisonNumber" ON vendor_comparisons ("ComparisonNumber");
        CREATE INDEX "IX_vendor_comparisons_Status" ON vendor_comparisons ("Status");
        CREATE INDEX "IX_vendor_comparisons_RFQId" ON vendor_comparisons ("RFQId");
    END IF;

    -- Add Foreign Key from RFQ to VendorComparison
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'FK_request_for_quotations_vendor_comparisons_ComparisonId'
    ) THEN
        ALTER TABLE request_for_quotations
        ADD CONSTRAINT "FK_request_for_quotations_vendor_comparisons_ComparisonId"
        FOREIGN KEY ("ComparisonId") REFERENCES vendor_comparisons("Id") ON DELETE SET NULL;
    END IF;

    -- 6. Vendor Comparison Entries Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_comparison_entries'
    ) THEN
        CREATE TABLE vendor_comparison_entries (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VendorComparisonId" integer NOT NULL REFERENCES vendor_comparisons("Id") ON DELETE CASCADE,
            "VendorId" integer NOT NULL REFERENCES vendors("Id") ON DELETE RESTRICT,
            "VendorName" character varying(256) NOT NULL,
            "QuotationRef" character varying(128) NOT NULL DEFAULT '',
            "VendorQuotationId" integer NULL REFERENCES vendor_quotations("Id") ON DELETE SET NULL,
            "UnitPrice" numeric(18,4) NOT NULL DEFAULT 0,
            "TaxPercent" numeric(5,2) NOT NULL DEFAULT 0,
            "DiscountPercent" numeric(5,2) NOT NULL DEFAULT 0,
            "DeliveryTimeDays" integer NOT NULL DEFAULT 0,
            "LeadTime" character varying(128) NOT NULL DEFAULT '',
            "WarrantyPeriod" character varying(128) NOT NULL DEFAULT '',
            "PaymentTerms" character varying(500) NOT NULL DEFAULT '',
            "TotalCost" numeric(18,4) NOT NULL DEFAULT 0,
            "Ranking" integer NOT NULL DEFAULT 0,
            "IsLowestPrice" boolean NOT NULL DEFAULT false,
            "IsBestDelivery" boolean NOT NULL DEFAULT false,
            "RecommendationScore" double precision NOT NULL DEFAULT 0,
            "Remarks" character varying(2000) NOT NULL DEFAULT ''
        );

        CREATE INDEX "IX_vendor_comparison_entries_VendorComparisonId" ON vendor_comparison_entries ("VendorComparisonId");
        CREATE INDEX "IX_vendor_comparison_entries_VendorId" ON vendor_comparison_entries ("VendorId");
    END IF;

    -- 7. Vendor Comparison Status Histories Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_comparison_status_histories'
    ) THEN
        CREATE TABLE vendor_comparison_status_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VendorComparisonId" integer NOT NULL REFERENCES vendor_comparisons("Id") ON DELETE CASCADE,
            "Status" character varying(64) NOT NULL,
            "PreviousStatus" character varying(64) NULL,
            "User" character varying(256) NOT NULL DEFAULT '',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Date" timestamp with time zone NOT NULL DEFAULT NOW()
        );

        CREATE INDEX "IX_vendor_comparison_status_histories_VendorComparisonId_Date" ON vendor_comparison_status_histories ("VendorComparisonId", "Date");
    END IF;

END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "vendor_comparison_status_histories");
            migrationBuilder.DropTable(name: "vendor_comparison_entries");
            migrationBuilder.DropTable(name: "vendor_comparisons");
            migrationBuilder.DropTable(name: "vendor_quotation_lines");
            migrationBuilder.DropTable(name: "vendor_quotations");
            migrationBuilder.DropTable(name: "vendor_comparison_document_sequences");
            migrationBuilder.DropTable(name: "vendor_quotation_document_sequences");
        }
    }
}
