using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260828000000_AddProcurementPhase6QualityControl")]
    public partial class AddProcurementPhase6QualityControl : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    -- 1. Document Sequence
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'quality_control_document_sequences'
    ) THEN
        CREATE TABLE quality_control_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Prefix" character varying(64) NOT NULL,
            "LastSequence" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_quality_control_document_sequences_Prefix" ON quality_control_document_sequences ("Prefix");
    END IF;

    -- 2. Incoming Inspections
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'incoming_inspections'
    ) THEN
        CREATE TABLE incoming_inspections (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "InspectionNumber" character varying(64) NOT NULL,
            "InspectionDate" timestamp with time zone NOT NULL,
            "SupplierId" integer NOT NULL DEFAULT 0,
            "SupplierName" character varying(256) NOT NULL DEFAULT '',
            "VendorId" integer NOT NULL DEFAULT 0,
            "VendorName" character varying(256) NOT NULL DEFAULT '',
            "PurchaseOrderId" integer NOT NULL DEFAULT 0,
            "PurchaseOrderNumber" character varying(64) NOT NULL DEFAULT '',
            "GRNId" integer NOT NULL DEFAULT 0,
            "GRNNumber" character varying(64) NOT NULL DEFAULT '',
            "MaterialId" integer NOT NULL DEFAULT 0,
            "MaterialCode" character varying(64) NOT NULL DEFAULT '',
            "MaterialName" character varying(256) NOT NULL DEFAULT '',
            "BatchNumber" character varying(128) NOT NULL DEFAULT '',
            "WarehouseId" integer NOT NULL DEFAULT 0,
            "WarehouseName" character varying(256) NOT NULL DEFAULT '',
            "Inspector" character varying(256) NOT NULL DEFAULT '',
            "InspectionType" character varying(64) NOT NULL DEFAULT 'Visual',
            "InspectionMethod" character varying(64) NOT NULL DEFAULT 'Sampling',
            "SamplingQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "AcceptedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "RejectedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "PendingQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "InspectionResult" character varying(64) NOT NULL DEFAULT 'Pending',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_incoming_inspections_InspectionNumber" ON incoming_inspections ("InspectionNumber");
        CREATE INDEX "IX_incoming_inspections_Status" ON incoming_inspections ("Status");
        CREATE INDEX "IX_incoming_inspections_PurchaseOrderId" ON incoming_inspections ("PurchaseOrderId");
        CREATE INDEX "IX_incoming_inspections_GRNId" ON incoming_inspections ("GRNId");
    END IF;

    -- 3. Incoming Checklist Items
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'incoming_checklist_items'
    ) THEN
        CREATE TABLE incoming_checklist_items (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "IncomingInspectionId" integer NOT NULL REFERENCES incoming_inspections("Id") ON DELETE CASCADE,
            "Parameter" character varying(256) NOT NULL,
            "Specification" character varying(256) NOT NULL DEFAULT '',
            "ActualValue" character varying(256) NOT NULL DEFAULT '',
            "Result" character varying(64) NOT NULL DEFAULT 'Pending',
            "Remarks" character varying(2000) NOT NULL DEFAULT ''
        );

        CREATE INDEX "IX_incoming_checklist_items_IncomingInspectionId" ON incoming_checklist_items ("IncomingInspectionId");
    END IF;

    -- 4. In Process Checks
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'in_process_checks'
    ) THEN
        CREATE TABLE in_process_checks (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "QCNumber" character varying(64) NOT NULL,
            "ProductionEntryId" integer NOT NULL DEFAULT 0,
            "ProductionEntryNumber" character varying(64) NOT NULL DEFAULT '',
            "WorkOrderId" integer NOT NULL DEFAULT 0,
            "WorkOrderNumber" character varying(64) NOT NULL DEFAULT '',
            "MachineId" integer NOT NULL DEFAULT 0,
            "MachineCode" character varying(64) NOT NULL DEFAULT '',
            "MachineName" character varying(256) NOT NULL DEFAULT '',
            "Operator" character varying(256) NOT NULL DEFAULT '',
            "Shift" character varying(32) NOT NULL DEFAULT 'A',
            "Stage" character varying(128) NOT NULL DEFAULT '',
            "ProductId" integer NOT NULL DEFAULT 0,
            "ProductCode" character varying(64) NOT NULL DEFAULT '',
            "ProductName" character varying(256) NOT NULL DEFAULT '',
            "BatchNumber" character varying(128) NOT NULL DEFAULT '',
            "Parameter" character varying(256) NOT NULL DEFAULT '',
            "Tolerance" character varying(128) NOT NULL DEFAULT '',
            "ExpectedValue" character varying(128) NOT NULL DEFAULT '',
            "ActualValue" character varying(128) NOT NULL DEFAULT '',
            "Result" character varying(64) NOT NULL DEFAULT 'Pending',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_in_process_checks_QCNumber" ON in_process_checks ("QCNumber");
        CREATE INDEX "IX_in_process_checks_Status" ON in_process_checks ("Status");
    END IF;

    -- 5. Final Inspections
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'final_inspections'
    ) THEN
        CREATE TABLE final_inspections (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "InspectionNumber" character varying(64) NOT NULL,
            "InspectionDate" timestamp with time zone NOT NULL,
            "FinishedProductId" integer NOT NULL DEFAULT 0,
            "FinishedProductCode" character varying(64) NOT NULL DEFAULT '',
            "FinishedProductName" character varying(256) NOT NULL DEFAULT '',
            "ProductionEntryId" integer NOT NULL DEFAULT 0,
            "ProductionEntryNumber" character varying(64) NOT NULL DEFAULT '',
            "ProductionBatch" character varying(128) NOT NULL DEFAULT '',
            "Inspector" character varying(256) NOT NULL DEFAULT '',
            "Dimension" character varying(128) NOT NULL DEFAULT '',
            "Weight" character varying(128) NOT NULL DEFAULT '',
            "Strength" character varying(128) NOT NULL DEFAULT '',
            "SurfaceFinish" character varying(128) NOT NULL DEFAULT '',
            "VisualCheck" character varying(128) NOT NULL DEFAULT '',
            "AcceptedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "RejectedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "TestCertificateId" integer NULL,
            "LoadTestId" integer NULL,
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_final_inspections_InspectionNumber" ON final_inspections ("InspectionNumber");
        CREATE INDEX "IX_final_inspections_Status" ON final_inspections ("Status");
    END IF;

    -- 6. Final Inspection Parameters
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'final_inspection_parameters'
    ) THEN
        CREATE TABLE final_inspection_parameters (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "FinalInspectionId" integer NOT NULL REFERENCES final_inspections("Id") ON DELETE CASCADE,
            "Name" character varying(256) NOT NULL,
            "Expected" character varying(256) NOT NULL DEFAULT '',
            "Actual" character varying(256) NOT NULL DEFAULT '',
            "Result" character varying(64) NOT NULL DEFAULT 'Pending'
        );

        CREATE INDEX "IX_final_inspection_parameters_FinalInspectionId" ON final_inspection_parameters ("FinalInspectionId");
    END IF;

    -- 7. Load Test Reports
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'load_test_reports'
    ) THEN
        CREATE TABLE load_test_reports (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ReportNumber" character varying(64) NOT NULL,
            "TestDate" timestamp with time zone NOT NULL,
            "ProductId" integer NOT NULL DEFAULT 0,
            "ProductCode" character varying(64) NOT NULL DEFAULT '',
            "ProductName" character varying(256) NOT NULL DEFAULT '',
            "FinalInspectionId" integer NOT NULL DEFAULT 0,
            "FinalInspectionNumber" character varying(64) NOT NULL DEFAULT '',
            "MachineId" integer NOT NULL DEFAULT 0,
            "MachineCode" character varying(64) NOT NULL DEFAULT '',
            "MachineName" character varying(256) NOT NULL DEFAULT '',
            "LoadCapacity" numeric(18,4) NOT NULL DEFAULT 0,
            "AppliedLoad" numeric(18,4) NOT NULL DEFAULT 0,
            "DurationMinutes" integer NOT NULL DEFAULT 0,
            "Result" character varying(64) NOT NULL DEFAULT 'Pending',
            "PassFail" character varying(32) NOT NULL DEFAULT 'Pending',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_load_test_reports_ReportNumber" ON load_test_reports ("ReportNumber");
        CREATE INDEX "IX_load_test_reports_FinalInspectionId" ON load_test_reports ("FinalInspectionId");
    END IF;

    -- 8. Test Certificates
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'test_certificates'
    ) THEN
        CREATE TABLE test_certificates (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CertificateNumber" character varying(64) NOT NULL,
            "CertificateDate" timestamp with time zone NOT NULL,
            "CustomerId" integer NOT NULL DEFAULT 0,
            "CustomerName" character varying(256) NOT NULL DEFAULT '',
            "ProductId" integer NOT NULL DEFAULT 0,
            "ProductCode" character varying(64) NOT NULL DEFAULT '',
            "ProductName" character varying(256) NOT NULL DEFAULT '',
            "FinalInspectionId" integer NOT NULL DEFAULT 0,
            "FinalInspectionNumber" character varying(64) NOT NULL DEFAULT '',
            "LoadTestId" integer NULL,
            "LoadTestNumber" character varying(64) NULL,
            "BatchNumber" character varying(128) NOT NULL DEFAULT '',
            "IssuedBy" character varying(256) NOT NULL DEFAULT '',
            "ApprovedBy" character varying(256) NULL,
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "ExpiryDate" timestamp with time zone NULL,
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_test_certificates_CertificateNumber" ON test_certificates ("CertificateNumber");
        CREATE INDEX "IX_test_certificates_Status" ON test_certificates ("Status");
        CREATE INDEX "IX_test_certificates_FinalInspectionId" ON test_certificates ("FinalInspectionId");
    END IF;

    -- 9. Rejection Analyses
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'rejection_analyses'
    ) THEN
        CREATE TABLE rejection_analyses (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "RejectionNumber" character varying(64) NOT NULL,
            "RejectionDate" timestamp with time zone NOT NULL,
            "Source" character varying(64) NOT NULL DEFAULT 'Incoming',
            "SourceRecordId" integer NOT NULL DEFAULT 0,
            "SourceRecordNumber" character varying(64) NOT NULL DEFAULT '',
            "MaterialId" integer NULL,
            "MaterialCode" character varying(64) NULL,
            "MaterialName" character varying(256) NULL,
            "ProductId" integer NULL,
            "ProductCode" character varying(64) NULL,
            "ProductName" character varying(256) NULL,
            "BatchNumber" character varying(128) NOT NULL DEFAULT '',
            "Quantity" numeric(18,4) NOT NULL DEFAULT 0,
            "Reason" character varying(500) NOT NULL DEFAULT '',
            "RootCause" character varying(1000) NOT NULL DEFAULT '',
            "Department" character varying(256) NOT NULL DEFAULT '',
            "Operator" character varying(256) NOT NULL DEFAULT '',
            "MachineId" integer NULL,
            "MachineCode" character varying(64) NULL,
            "MachineName" character varying(256) NULL,
            "SupplierName" character varying(256) NULL,
            "CorrectiveAction" character varying(1000) NOT NULL DEFAULT '',
            "PreventiveAction" character varying(1000) NOT NULL DEFAULT '',
            "Status" character varying(64) NOT NULL DEFAULT 'Open',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_rejection_analyses_RejectionNumber" ON rejection_analyses ("RejectionNumber");
        CREATE INDEX "IX_rejection_analyses_Status" ON rejection_analyses ("Status");
        CREATE INDEX "IX_rejection_analyses_Source" ON rejection_analyses ("Source");
    END IF;

END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "rejection_analyses");
            migrationBuilder.DropTable(name: "test_certificates");
            migrationBuilder.DropTable(name: "load_test_reports");
            migrationBuilder.DropTable(name: "final_inspection_parameters");
            migrationBuilder.DropTable(name: "final_inspections");
            migrationBuilder.DropTable(name: "in_process_checks");
            migrationBuilder.DropTable(name: "incoming_checklist_items");
            migrationBuilder.DropTable(name: "incoming_inspections");
            migrationBuilder.DropTable(name: "quality_control_document_sequences");
        }
    }
}
