using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260831000000_AddProcurementAuditTrailAndReports")]
    public partial class AddProcurementAuditTrailAndReports : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'procurement_audit_trail_entries'
    ) THEN
        CREATE TABLE procurement_audit_trail_entries (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Module" character varying(64) NOT NULL,
            "Action" character varying(128) NOT NULL,
            "EntityId" integer NOT NULL DEFAULT 0,
            "EntityNumber" character varying(64) NOT NULL DEFAULT '',
            "User" character varying(256) NOT NULL DEFAULT '',
            "Date" timestamp with time zone NOT NULL DEFAULT NOW(),
            "OldValue" character varying(1000) NOT NULL DEFAULT '',
            "NewValue" character varying(1000) NOT NULL DEFAULT '',
            "Remarks" character varying(2000) NOT NULL DEFAULT ''
        );

        CREATE INDEX "IX_procurement_audit_trail_entries_Module" ON procurement_audit_trail_entries ("Module");
        CREATE INDEX "IX_procurement_audit_trail_entries_Action" ON procurement_audit_trail_entries ("Action");
        CREATE INDEX "IX_procurement_audit_trail_entries_EntityId" ON procurement_audit_trail_entries ("EntityId");
        CREATE INDEX "IX_procurement_audit_trail_entries_EntityNumber" ON procurement_audit_trail_entries ("EntityNumber");
    END IF;
END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "procurement_audit_trail_entries");
        }
    }
}
