using System;
using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260921120000_AddErpRolesAndAlignUsers")]
    public partial class AddErpRolesAndAlignUsers : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    -- 1. Create erp_roles table
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = 'erp_roles'
                    ) THEN
                        CREATE TABLE erp_roles (
                            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name character varying(128) NOT NULL,
                            description character varying(256) NULL,
                            is_active boolean NOT NULL DEFAULT true,
                            created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                            updated_at timestamp with time zone NULL
                        );

                        CREATE UNIQUE INDEX "IX_erp_roles_name" ON erp_roles (name);
                    END IF;

                    -- 2. Seed Admin role (id = 1)
                    INSERT INTO erp_roles (id, name, description, is_active, created_at)
                    VALUES (1, 'Admin', 'System Administrator', true, '2026-01-01 00:00:00+00'::timestamp with time zone)
                    ON CONFLICT (id) DO NOTHING;

                    -- 3. Align users table with presence fields if users table exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = 'users'
                    ) THEN
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'users' AND column_name = 'is_online'
                        ) THEN
                            ALTER TABLE users ADD COLUMN is_online boolean NOT NULL DEFAULT false;
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'users' AND column_name = 'last_active_at'
                        ) THEN
                            ALTER TABLE users ADD COLUMN last_active_at timestamp with time zone NULL;
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'users' AND column_name = 'first_login_at'
                        ) THEN
                            ALTER TABLE users ADD COLUMN first_login_at timestamp with time zone NULL;
                        END IF;
                    END IF;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = 'erp_roles'
                    ) THEN
                        DROP TABLE erp_roles CASCADE;
                    END IF;
                END $$;
                """);
        }
    }
}
