using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddDiscountApprovals : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'discount_approval_document_sequences'
    ) THEN
        CREATE TABLE discount_approval_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "FinancialYear" integer NOT NULL,
            "Prefix" character varying(16) NOT NULL,
            "LastNumber" integer NOT NULL,
            "CreatedOn" timestamp with time zone NOT NULL
        );
    END IF;

    ALTER TABLE discount_approval_document_sequences ADD COLUMN IF NOT EXISTS "FinancialYear" integer NOT NULL DEFAULT 0;
    ALTER TABLE discount_approval_document_sequences ADD COLUMN IF NOT EXISTS "Prefix" character varying(16) NOT NULL DEFAULT 'DA';
    ALTER TABLE discount_approval_document_sequences ADD COLUMN IF NOT EXISTS "LastNumber" integer NOT NULL DEFAULT 0;
    ALTER TABLE discount_approval_document_sequences ADD COLUMN IF NOT EXISTS "CreatedOn" timestamp with time zone NOT NULL DEFAULT NOW();

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public'
          AND indexname = 'IX_discount_approval_document_sequences_FinancialYear_Prefix'
    ) THEN
        CREATE UNIQUE INDEX "IX_discount_approval_document_sequences_FinancialYear_Prefix"
            ON discount_approval_document_sequences ("FinancialYear", "Prefix");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'discount_approvals'
    ) THEN
        CREATE TABLE discount_approvals (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ApprovalNumber" character varying(64) NOT NULL,
            "RequestDate" date NOT NULL,
            "SourceType" character varying(64) NOT NULL,
            "QuotationId" integer NULL,
            "QuotationNumber" character varying(64) NOT NULL DEFAULT '',
            "SalesOrderId" integer NULL,
            "SalesOrderNumber" character varying(64) NOT NULL DEFAULT '',
            "PriceListId" integer NULL,
            "CustomerName" character varying(256) NOT NULL,
            "CustomerCategory" character varying(64) NOT NULL,
            "SalesPersonUserId" integer NOT NULL,
            "RequestedDiscountPercentage" numeric(9,4) NOT NULL,
            "ApprovedDiscountPercentage" numeric(9,4) NULL,
            "RequestedAmount" numeric(18,2) NOT NULL,
            "ApprovedAmount" numeric(18,2) NULL,
            "ApprovalLevel" character varying(64) NOT NULL,
            "Priority" character varying(64) NOT NULL,
            "Status" character varying(64) NOT NULL,
            "Reason" character varying(2000) NOT NULL DEFAULT '',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "CreatedBy" character varying(64) NOT NULL DEFAULT '',
            "CreatedDate" timestamp with time zone NOT NULL,
            "UpdatedBy" character varying(64) NOT NULL DEFAULT '',
            "UpdatedDate" timestamp with time zone NOT NULL,
            "IsDeleted" boolean NOT NULL DEFAULT FALSE
        );
    END IF;

    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "ApprovalNumber" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "RequestDate" date NOT NULL DEFAULT CURRENT_DATE;
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "SourceType" character varying(64) NOT NULL DEFAULT 'SalesOrder';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "QuotationId" integer NULL;
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "QuotationNumber" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "SalesOrderId" integer NULL;
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "SalesOrderNumber" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "PriceListId" integer NULL;
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "CustomerName" character varying(256) NOT NULL DEFAULT '';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "CustomerCategory" character varying(64) NOT NULL DEFAULT 'Standard';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "SalesPersonUserId" integer NOT NULL DEFAULT 0;
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "RequestedDiscountPercentage" numeric(9,4) NOT NULL DEFAULT 0;
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "ApprovedDiscountPercentage" numeric(9,4) NULL;
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "RequestedAmount" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "ApprovedAmount" numeric(18,2) NULL;
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "ApprovalLevel" character varying(64) NOT NULL DEFAULT 'Manager';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "Priority" character varying(64) NOT NULL DEFAULT 'Normal';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "Status" character varying(64) NOT NULL DEFAULT 'Pending';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "Reason" character varying(2000) NOT NULL DEFAULT '';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "Remarks" character varying(2000) NOT NULL DEFAULT '';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "CreatedBy" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "CreatedDate" timestamp with time zone NOT NULL DEFAULT NOW();
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "UpdatedBy" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "UpdatedDate" timestamp with time zone NOT NULL DEFAULT NOW();
    ALTER TABLE discount_approvals ADD COLUMN IF NOT EXISTS "IsDeleted" boolean NOT NULL DEFAULT FALSE;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_ApprovalNumber') THEN
        CREATE UNIQUE INDEX "IX_discount_approvals_ApprovalNumber" ON discount_approvals ("ApprovalNumber");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_Status') THEN
        CREATE INDEX "IX_discount_approvals_Status" ON discount_approvals ("Status");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_Priority') THEN
        CREATE INDEX "IX_discount_approvals_Priority" ON discount_approvals ("Priority");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_ApprovalLevel') THEN
        CREATE INDEX "IX_discount_approvals_ApprovalLevel" ON discount_approvals ("ApprovalLevel");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_SourceType') THEN
        CREATE INDEX "IX_discount_approvals_SourceType" ON discount_approvals ("SourceType");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_CustomerCategory') THEN
        CREATE INDEX "IX_discount_approvals_CustomerCategory" ON discount_approvals ("CustomerCategory");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_SalesPersonUserId') THEN
        CREATE INDEX "IX_discount_approvals_SalesPersonUserId" ON discount_approvals ("SalesPersonUserId");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_RequestDate') THEN
        CREATE INDEX "IX_discount_approvals_RequestDate" ON discount_approvals ("RequestDate");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_IsDeleted') THEN
        CREATE INDEX "IX_discount_approvals_IsDeleted" ON discount_approvals ("IsDeleted");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_SalesOrderId') THEN
        CREATE INDEX "IX_discount_approvals_SalesOrderId" ON discount_approvals ("SalesOrderId");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_PriceListId') THEN
        CREATE INDEX "IX_discount_approvals_PriceListId" ON discount_approvals ("PriceListId");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_discount_approvals_QuotationId') THEN
        CREATE INDEX "IX_discount_approvals_QuotationId" ON discount_approvals ("QuotationId");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'discount_approval_history'
    ) THEN
        CREATE TABLE discount_approval_history (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "DiscountApprovalId" integer NOT NULL,
            "Action" character varying(64) NOT NULL,
            "OldStatus" character varying(64) NOT NULL DEFAULT '',
            "NewStatus" character varying(64) NOT NULL DEFAULT '',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "PerformedBy" character varying(64) NOT NULL DEFAULT '',
            "PerformedOn" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_discount_approval_history_discount_approvals_DiscountApprovalId"
                FOREIGN KEY ("DiscountApprovalId") REFERENCES discount_approvals ("Id") ON DELETE CASCADE
        );
    END IF;

    ALTER TABLE discount_approval_history ADD COLUMN IF NOT EXISTS "DiscountApprovalId" integer;
    ALTER TABLE discount_approval_history ADD COLUMN IF NOT EXISTS "Action" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE discount_approval_history ADD COLUMN IF NOT EXISTS "OldStatus" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE discount_approval_history ADD COLUMN IF NOT EXISTS "NewStatus" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE discount_approval_history ADD COLUMN IF NOT EXISTS "Remarks" character varying(2000) NOT NULL DEFAULT '';
    ALTER TABLE discount_approval_history ADD COLUMN IF NOT EXISTS "PerformedBy" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE discount_approval_history ADD COLUMN IF NOT EXISTS "PerformedOn" timestamp with time zone NOT NULL DEFAULT NOW();

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = 'discount_approval_history'
          AND constraint_name = 'FK_discount_approval_history_discount_approvals_DiscountApprovalId'
    ) THEN
        ALTER TABLE discount_approval_history
            ADD CONSTRAINT "FK_discount_approval_history_discount_approvals_DiscountApprovalId"
            FOREIGN KEY ("DiscountApprovalId") REFERENCES discount_approvals ("Id") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE indexname = 'IX_discount_approval_history_DiscountApprovalId_PerformedOn'
    ) THEN
        CREATE INDEX "IX_discount_approval_history_DiscountApprovalId_PerformedOn"
            ON discount_approval_history ("DiscountApprovalId", "PerformedOn");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'discount_approval_comments'
    ) THEN
        CREATE TABLE discount_approval_comments (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "DiscountApprovalId" integer NOT NULL,
            "Comment" character varying(2000) NOT NULL,
            "CommentedBy" character varying(64) NOT NULL DEFAULT '',
            "CommentedOn" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_discount_approval_comments_discount_approvals_DiscountApprovalId"
                FOREIGN KEY ("DiscountApprovalId") REFERENCES discount_approvals ("Id") ON DELETE CASCADE
        );
    END IF;

    ALTER TABLE discount_approval_comments ADD COLUMN IF NOT EXISTS "DiscountApprovalId" integer;
    ALTER TABLE discount_approval_comments ADD COLUMN IF NOT EXISTS "Comment" character varying(2000) NOT NULL DEFAULT '';
    ALTER TABLE discount_approval_comments ADD COLUMN IF NOT EXISTS "CommentedBy" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE discount_approval_comments ADD COLUMN IF NOT EXISTS "CommentedOn" timestamp with time zone NOT NULL DEFAULT NOW();

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = 'discount_approval_comments'
          AND constraint_name = 'FK_discount_approval_comments_discount_approvals_DiscountApprovalId'
    ) THEN
        ALTER TABLE discount_approval_comments
            ADD CONSTRAINT "FK_discount_approval_comments_discount_approvals_DiscountApprovalId"
            FOREIGN KEY ("DiscountApprovalId") REFERENCES discount_approvals ("Id") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE indexname = 'IX_discount_approval_comments_DiscountApprovalId_CommentedOn'
    ) THEN
        CREATE INDEX "IX_discount_approval_comments_DiscountApprovalId_CommentedOn"
            ON discount_approval_comments ("DiscountApprovalId", "CommentedOn");
    END IF;
END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP TABLE IF EXISTS discount_approval_comments;
DROP TABLE IF EXISTS discount_approval_history;
DROP TABLE IF EXISTS discount_approvals;
DROP TABLE IF EXISTS discount_approval_document_sequences;
""");
        }
    }
}
