using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260921000000_AddUsersTableToErp")]
    public partial class AddUsersTableToErp : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = 'users'
                    ) THEN
                        CREATE TABLE users (
                            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            full_name character varying(256) NOT NULL,
                            email character varying(256) NOT NULL,
                            phone character varying(64) NULL,
                            password_hash character varying(512) NOT NULL,
                            role_id integer NULL,
                            is_active boolean NOT NULL DEFAULT true,
                            created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                            updated_at timestamp with time zone NULL
                        );

                        CREATE UNIQUE INDEX "IX_users_email" ON users (email);
                    END IF;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "users");
        }
    }
}
