using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddPerformanceDashboard : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='performance_snapshots') THEN
        CREATE TABLE performance_snapshots (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "SnapshotDate" date NOT NULL, "PeriodType" character varying(32) NOT NULL,
            "SalesPersonUserId" integer NULL, "SalesTeam" character varying(128) NOT NULL,
            "Branch" character varying(128) NOT NULL, "RegionalManager" character varying(128) NOT NULL,
            "TotalSalesOrders" integer NOT NULL, "ConfirmedSalesOrders" integer NOT NULL,
            "CompletedSalesOrders" integer NOT NULL, "CancelledSalesOrders" integer NOT NULL,
            "SalesOrderAmount" numeric(18,2) NOT NULL, "ProformaInvoiceCount" integer NOT NULL,
            "ApprovedProformaInvoices" integer NOT NULL, "ConvertedProformaInvoices" integer NOT NULL,
            "ProformaAmount" numeric(18,2) NOT NULL, "AdvancePaymentReceived" numeric(18,2) NOT NULL,
            "AdvancePaymentApplied" numeric(18,2) NOT NULL, "OutstandingAdvance" numeric(18,2) NOT NULL,
            "AssignedTarget" numeric(18,2) NOT NULL, "AchievedTarget" numeric(18,2) NOT NULL,
            "AchievementPercentage" numeric(9,2) NOT NULL, "CollectionPercentage" numeric(9,2) NOT NULL,
            "ConversionPercentage" numeric(9,2) NOT NULL, "CreatedOn" timestamp with time zone NOT NULL
        );
    END IF;

    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "SnapshotDate" date NOT NULL DEFAULT CURRENT_DATE;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "PeriodType" character varying(32) NOT NULL DEFAULT 'Monthly';
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "SalesPersonUserId" integer NULL;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "SalesTeam" character varying(128) NOT NULL DEFAULT '';
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "Branch" character varying(128) NOT NULL DEFAULT '';
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "RegionalManager" character varying(128) NOT NULL DEFAULT '';
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "TotalSalesOrders" integer NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "ConfirmedSalesOrders" integer NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "CompletedSalesOrders" integer NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "CancelledSalesOrders" integer NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "SalesOrderAmount" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "ProformaInvoiceCount" integer NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "ApprovedProformaInvoices" integer NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "ConvertedProformaInvoices" integer NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "ProformaAmount" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "AdvancePaymentReceived" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "AdvancePaymentApplied" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "OutstandingAdvance" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "AssignedTarget" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "AchievedTarget" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "AchievementPercentage" numeric(9,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "CollectionPercentage" numeric(9,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "ConversionPercentage" numeric(9,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_snapshots ADD COLUMN IF NOT EXISTS "CreatedOn" timestamp with time zone NOT NULL DEFAULT NOW();

    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='performance_history') THEN
        CREATE TABLE performance_history (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "SalesPersonUserId" integer NULL, "PeriodStart" date NOT NULL, "PeriodEnd" date NOT NULL,
            "MetricName" character varying(128) NOT NULL, "OldValue" numeric(18,2) NOT NULL,
            "NewValue" numeric(18,2) NOT NULL, "Remarks" character varying(2000) NOT NULL,
            "RecordedOn" timestamp with time zone NOT NULL
        );
    END IF;
    ALTER TABLE performance_history ADD COLUMN IF NOT EXISTS "SalesPersonUserId" integer NULL;
    ALTER TABLE performance_history ADD COLUMN IF NOT EXISTS "PeriodStart" date NOT NULL DEFAULT CURRENT_DATE;
    ALTER TABLE performance_history ADD COLUMN IF NOT EXISTS "PeriodEnd" date NOT NULL DEFAULT CURRENT_DATE;
    ALTER TABLE performance_history ADD COLUMN IF NOT EXISTS "MetricName" character varying(128) NOT NULL DEFAULT '';
    ALTER TABLE performance_history ADD COLUMN IF NOT EXISTS "OldValue" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_history ADD COLUMN IF NOT EXISTS "NewValue" numeric(18,2) NOT NULL DEFAULT 0;
    ALTER TABLE performance_history ADD COLUMN IF NOT EXISTS "Remarks" character varying(2000) NOT NULL DEFAULT '';
    ALTER TABLE performance_history ADD COLUMN IF NOT EXISTS "RecordedOn" timestamp with time zone NOT NULL DEFAULT NOW();

    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='performance_export_history') THEN
        CREATE TABLE performance_export_history (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ReportName" character varying(256) NOT NULL, "GeneratedBy" character varying(64) NOT NULL,
            "GeneratedOn" timestamp with time zone NOT NULL, "FileName" character varying(512) NOT NULL,
            "ExportType" character varying(32) NOT NULL
        );
    END IF;
    ALTER TABLE performance_export_history ADD COLUMN IF NOT EXISTS "ReportName" character varying(256) NOT NULL DEFAULT '';
    ALTER TABLE performance_export_history ADD COLUMN IF NOT EXISTS "GeneratedBy" character varying(64) NOT NULL DEFAULT '';
    ALTER TABLE performance_export_history ADD COLUMN IF NOT EXISTS "GeneratedOn" timestamp with time zone NOT NULL DEFAULT NOW();
    ALTER TABLE performance_export_history ADD COLUMN IF NOT EXISTS "FileName" character varying(512) NOT NULL DEFAULT '';
    ALTER TABLE performance_export_history ADD COLUMN IF NOT EXISTS "ExportType" character varying(32) NOT NULL DEFAULT 'csv';

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_performance_snapshots_SnapshotDate_PeriodType_SalesPersonUs~') THEN
        CREATE INDEX "IX_performance_snapshots_SnapshotDate_PeriodType_SalesPersonUs~"
            ON performance_snapshots ("SnapshotDate", "PeriodType", "SalesPersonUserId");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_performance_snapshots_SalesPersonUserId') THEN
        CREATE INDEX "IX_performance_snapshots_SalesPersonUserId" ON performance_snapshots ("SalesPersonUserId");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_performance_history_SalesPersonUserId_PeriodStart_PeriodEnd') THEN
        CREATE INDEX "IX_performance_history_SalesPersonUserId_PeriodStart_PeriodEnd"
            ON performance_history ("SalesPersonUserId", "PeriodStart", "PeriodEnd");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_performance_history_RecordedOn') THEN
        CREATE INDEX "IX_performance_history_RecordedOn" ON performance_history ("RecordedOn");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_performance_export_history_GeneratedBy') THEN
        CREATE INDEX "IX_performance_export_history_GeneratedBy" ON performance_export_history ("GeneratedBy");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='IX_performance_export_history_GeneratedOn') THEN
        CREATE INDEX "IX_performance_export_history_GeneratedOn" ON performance_export_history ("GeneratedOn");
    END IF;
END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP TABLE IF EXISTS performance_export_history;
DROP TABLE IF EXISTS performance_history;
DROP TABLE IF EXISTS performance_snapshots;
""");
        }
    }
}
