using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERP.Infrastructure.Migrations
{
    public partial class AdvancePaymentPhase2StatutoryAndIntegrations : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var sql = @"
DO $$
BEGIN
    -- 1. Company Bank Accounts Master Table
    CREATE TABLE IF NOT EXISTS public.bank_accounts (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ""AccountName"" character varying(100) NOT NULL,
        ""AccountNumber"" character varying(50) NOT NULL,
        ""BankName"" character varying(100) NOT NULL,
        ""Branch"" character varying(100) NOT NULL DEFAULT '',
        ""IfscCode"" character varying(20) NOT NULL DEFAULT '',
        ""AccountType"" character varying(30) NOT NULL DEFAULT 'Current',
        ""Currency"" character varying(10) NOT NULL DEFAULT 'INR',
        ""IsActive"" boolean NOT NULL DEFAULT true,
        ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT NOW()
    );

    -- Seed sample active bank accounts if empty
    IF NOT EXISTS (SELECT 1 FROM public.bank_accounts LIMIT 1) THEN
        INSERT INTO public.bank_accounts (""AccountName"", ""AccountNumber"", ""BankName"", ""Branch"", ""IfscCode"", ""AccountType"", ""Currency"", ""IsActive"", ""CreatedDate"")
        VALUES 
        ('Main Operating Account', '50200012345678', 'HDFC Bank', 'Nariman Point, Mumbai', 'HDFC0000060', 'Current', 'INR', true, NOW()),
        ('Export & Trade Account', '000405012345', 'ICICI Bank', 'BKC, Mumbai', 'ICIC0000004', 'Current', 'INR', true, NOW()),
        ('Escrow & Tax Account', '319800045678', 'State Bank of India', 'Fort, Mumbai', 'SBIN0000300', 'Current', 'INR', true, NOW());
    END IF;

    -- 2. Advance Payments Bank Linkage & Place of Supply
    ALTER TABLE public.advance_payments
    ADD COLUMN IF NOT EXISTS ""BankAccountId"" integer NULL REFERENCES public.bank_accounts(""Id"") ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS ""ReconciliationStatus"" character varying(32) NOT NULL DEFAULT 'Unreconciled',
    ADD COLUMN IF NOT EXISTS ""BankReconciledOn"" timestamp with time zone NULL,
    ADD COLUMN IF NOT EXISTS ""BankStatementReference"" character varying(100) NULL,
    ADD COLUMN IF NOT EXISTS ""PlaceOfSupply"" character varying(50) NOT NULL DEFAULT 'Maharashtra';

    CREATE INDEX IF NOT EXISTS ""IX_advance_payments_BankAccountId"" ON public.advance_payments (""BankAccountId"");

    -- 3. Statutory GST Receipt Vouchers Table
    CREATE TABLE IF NOT EXISTS public.advance_payment_receipt_vouchers (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ""VoucherNumber"" character varying(32) NOT NULL UNIQUE,
        ""AdvancePaymentId"" integer NOT NULL REFERENCES public.advance_payments(""Id"") ON DELETE CASCADE,
        ""CustomerId"" integer NOT NULL,
        ""CustomerName"" character varying(200) NOT NULL DEFAULT '',
        ""PlaceOfSupply"" character varying(50) NOT NULL,
        ""IsInterState"" boolean NOT NULL DEFAULT false,
        ""TaxableAmount"" numeric(18,2) NOT NULL,
        ""CgstRate"" numeric(5,2) NOT NULL DEFAULT 0,
        ""CgstAmount"" numeric(18,2) NOT NULL DEFAULT 0,
        ""SgstRate"" numeric(5,2) NOT NULL DEFAULT 0,
        ""SgstAmount"" numeric(18,2) NOT NULL DEFAULT 0,
        ""IgstRate"" numeric(5,2) NOT NULL DEFAULT 0,
        ""IgstAmount"" numeric(18,2) NOT NULL DEFAULT 0,
        ""TotalVoucherAmount"" numeric(18,2) NOT NULL,
        ""VoucherDate"" date NOT NULL,
        ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT NOW(),
        ""CreatedBy"" character varying(100) NOT NULL
    );

    CREATE INDEX IF NOT EXISTS ""IX_advance_payment_receipt_vouchers_AdvancePaymentId"" 
    ON public.advance_payment_receipt_vouchers (""AdvancePaymentId"");

    -- 4. Statutory GST Refund Vouchers Table
    CREATE TABLE IF NOT EXISTS public.advance_payment_refund_vouchers (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ""RefundVoucherNumber"" character varying(32) NOT NULL UNIQUE,
        ""AdvancePaymentId"" integer NOT NULL REFERENCES public.advance_payments(""Id"") ON DELETE RESTRICT,
        ""ReceiptVoucherId"" integer NOT NULL REFERENCES public.advance_payment_receipt_vouchers(""Id"") ON DELETE RESTRICT,
        ""RefundAmount"" numeric(18,2) NOT NULL,
        ""TaxRefundedAmount"" numeric(18,2) NOT NULL,
        ""RefundVoucherDate"" date NOT NULL,
        ""BankReferenceNumber"" character varying(64) NOT NULL,
        ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT NOW(),
        ""CreatedBy"" character varying(100) NOT NULL
    );

    CREATE INDEX IF NOT EXISTS ""IX_advance_payment_refund_vouchers_AdvancePaymentId"" 
    ON public.advance_payment_refund_vouchers (""AdvancePaymentId"");

    CREATE INDEX IF NOT EXISTS ""IX_advance_payment_refund_vouchers_ReceiptVoucherId"" 
    ON public.advance_payment_refund_vouchers (""ReceiptVoucherId"");

    -- 5. Proforma Invoices Settlement Columns
    ALTER TABLE public.proforma_invoices
    ADD COLUMN IF NOT EXISTS ""AdvanceReceivedAmount"" numeric(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ""PaymentStatus"" character varying(32) NOT NULL DEFAULT 'Unpaid';

    -- 6. Advance Payment Applications FX Tracking
    ALTER TABLE public.advance_payment_applications
    ADD COLUMN IF NOT EXISTS ""ExchangeRateAtAllocation"" numeric(18,4) NOT NULL DEFAULT 1.0000,
    ADD COLUMN IF NOT EXISTS ""RealizedFxGainLoss"" numeric(18,2) NOT NULL DEFAULT 0.00;

END $$;
";
            migrationBuilder.Sql(sql);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "advance_payment_refund_vouchers", schema: "public");
            migrationBuilder.DropTable(name: "advance_payment_receipt_vouchers", schema: "public");
            migrationBuilder.DropColumn(name: "BankAccountId", table: "advance_payments", schema: "public");
            migrationBuilder.DropColumn(name: "ReconciliationStatus", table: "advance_payments", schema: "public");
            migrationBuilder.DropColumn(name: "BankReconciledOn", table: "advance_payments", schema: "public");
            migrationBuilder.DropColumn(name: "BankStatementReference", table: "advance_payments", schema: "public");
            migrationBuilder.DropColumn(name: "PlaceOfSupply", table: "advance_payments", schema: "public");
            migrationBuilder.DropColumn(name: "AdvanceReceivedAmount", table: "proforma_invoices", schema: "public");
            migrationBuilder.DropColumn(name: "PaymentStatus", table: "proforma_invoices", schema: "public");
            migrationBuilder.DropColumn(name: "ExchangeRateAtAllocation", table: "advance_payment_applications", schema: "public");
            migrationBuilder.DropColumn(name: "RealizedFxGainLoss", table: "advance_payment_applications", schema: "public");
        }
    }
}
