using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260904153000_CanonicalQuotationWorkflow")]
    public partial class CanonicalQuotationWorkflow : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    -- 1. Create quotations table if not exists
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'quotations'
    ) THEN
        CREATE TABLE quotations (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "QuotationNumber" character varying(64) NOT NULL,
            "RevisionNumber" integer NOT NULL DEFAULT 1,
            "IsCurrentRevision" boolean NOT NULL DEFAULT true,
            "CustomerId" character varying(64) NOT NULL DEFAULT '',
            "CustomerName" character varying(256) NOT NULL,
            "ContactPerson" character varying(256) NOT NULL DEFAULT '',
            "CustomerEmail" character varying(256) NULL,
            "CustomerPhone" character varying(64) NULL,
            "BillingAddress" character varying(2000) NOT NULL DEFAULT '',
            "ShippingAddress" character varying(2000) NOT NULL DEFAULT '',
            "SalesPerson" character varying(256) NOT NULL DEFAULT '',
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "QuotationDate" date NOT NULL DEFAULT CURRENT_DATE,
            "ValidUntil" date NOT NULL DEFAULT (CURRENT_DATE + INTERVAL '14 days'),
            "Currency" character varying(16) NOT NULL DEFAULT 'INR',
            "ExchangeRate" numeric(18,6) NOT NULL DEFAULT 1.000000,
            "Subtotal" numeric(18,2) NOT NULL DEFAULT 0.00,
            "DiscountTotal" numeric(18,2) NOT NULL DEFAULT 0.00,
            "TaxTotal" numeric(18,2) NOT NULL DEFAULT 0.00,
            "FreightAmount" numeric(18,2) NOT NULL DEFAULT 0.00,
            "PackagingAmount" numeric(18,2) NOT NULL DEFAULT 0.00,
            "RoundOff" numeric(18,2) NOT NULL DEFAULT 0.00,
            "GrandTotal" numeric(18,2) NOT NULL DEFAULT 0.00,
            "PaymentTerms" character varying(128) NOT NULL DEFAULT 'Net 30',
            "DeliveryTerms" character varying(128) NOT NULL DEFAULT 'Ex-Works',
            "Notes" character varying(4000) NOT NULL DEFAULT '',
            "ClientPoNumber" character varying(128) NULL,
            "ClientAcceptedAt" timestamp with time zone NULL,
            "ClientPoAttachmentUrl" character varying(1024) NULL,
            "ConvertedSalesOrderId" integer NULL,
            "ConvertedSalesOrderNumber" character varying(64) NULL,
            "ConvertedOn" timestamp with time zone NULL,
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "CreatedDate" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedDate" timestamp with time zone NOT NULL DEFAULT NOW(),
            "IsDeleted" boolean NOT NULL DEFAULT false
        );
    END IF;

    -- Ensure all columns exist for existing installations
    ALTER TABLE quotations ADD COLUMN IF NOT EXISTS "RevisionNumber" integer NOT NULL DEFAULT 1;
    ALTER TABLE quotations ADD COLUMN IF NOT EXISTS "IsCurrentRevision" boolean NOT NULL DEFAULT true;
    ALTER TABLE quotations ADD COLUMN IF NOT EXISTS "FreightAmount" numeric(18,2) NOT NULL DEFAULT 0.00;
    ALTER TABLE quotations ADD COLUMN IF NOT EXISTS "PackagingAmount" numeric(18,2) NOT NULL DEFAULT 0.00;
    ALTER TABLE quotations ADD COLUMN IF NOT EXISTS "ClientPoNumber" character varying(128) NULL;
    ALTER TABLE quotations ADD COLUMN IF NOT EXISTS "ClientAcceptedAt" timestamp with time zone NULL;
    ALTER TABLE quotations ADD COLUMN IF NOT EXISTS "ClientPoAttachmentUrl" character varying(1024) NULL;
    ALTER TABLE quotations ADD COLUMN IF NOT EXISTS "ConvertedSalesOrderId" integer NULL;
    ALTER TABLE quotations ADD COLUMN IF NOT EXISTS "ConvertedSalesOrderNumber" character varying(64) NULL;
    ALTER TABLE quotations ADD COLUMN IF NOT EXISTS "ConvertedOn" timestamp with time zone NULL;

    -- 2. Create quotation_items table if not exists
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'quotation_items'
    ) THEN
        CREATE TABLE quotation_items (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "QuotationId" integer NOT NULL REFERENCES quotations("Id") ON DELETE CASCADE,
            "ProductId" integer NULL REFERENCES finished_goods("Id") ON DELETE SET NULL,
            "LineNumber" integer NOT NULL DEFAULT 1,
            "ItemCode" character varying(64) NOT NULL DEFAULT '',
            "ItemName" character varying(512) NOT NULL,
            "Description" character varying(2000) NOT NULL DEFAULT '',
            "Quantity" numeric(18,4) NOT NULL DEFAULT 1.0000,
            "Unit" character varying(32) NOT NULL DEFAULT 'NOS',
            "UnitPrice" numeric(18,2) NOT NULL DEFAULT 0.00,
            "DiscountPercent" numeric(9,4) NOT NULL DEFAULT 0.0000,
            "DiscountAmount" numeric(18,2) NOT NULL DEFAULT 0.00,
            "TaxPercent" numeric(9,4) NOT NULL DEFAULT 18.0000,
            "TaxAmount" numeric(18,2) NOT NULL DEFAULT 0.00,
            "LineTotal" numeric(18,2) NOT NULL DEFAULT 0.00,
            "SortOrder" integer NOT NULL DEFAULT 1
        );
    END IF;

    -- Ensure quotation_items columns exist for existing installations
    ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS "ProductId" integer NULL REFERENCES finished_goods("Id") ON DELETE SET NULL;

    -- 3. Required Filtered Unique Index to ensure single conversion under concurrency
    CREATE UNIQUE INDEX IF NOT EXISTS uq_quote_converted_so 
    ON quotations ("ConvertedSalesOrderId") 
    WHERE "ConvertedSalesOrderId" IS NOT NULL;

    -- 4. Additional Indexes
    CREATE INDEX IF NOT EXISTS "IX_quotations_QuotationNumber" ON quotations ("QuotationNumber");
    CREATE INDEX IF NOT EXISTS "IX_quotations_Status" ON quotations ("Status");
    CREATE INDEX IF NOT EXISTS "IX_quotations_IsCurrentRevision" ON quotations ("IsCurrentRevision");
    CREATE INDEX IF NOT EXISTS "IX_quotation_items_QuotationId" ON quotation_items ("QuotationId");
    CREATE INDEX IF NOT EXISTS "IX_quotation_items_ProductId" ON quotation_items ("ProductId");

END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP INDEX IF EXISTS uq_quote_converted_so;
DROP TABLE IF EXISTS quotation_items;
DROP TABLE IF EXISTS quotations;
""");
        }
    }
}
