using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddProcurementVendorMaster : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    -- 1. Vendor Document Sequences
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_document_sequences'
    ) THEN
        CREATE TABLE vendor_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Prefix" character varying(64) NOT NULL,
            "LastSequence" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_vendor_document_sequences_Prefix" ON vendor_document_sequences ("Prefix");
    END IF;

    -- 2. Vendor Payment Terms
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_payment_terms'
    ) THEN
        CREATE TABLE vendor_payment_terms (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Code" character varying(64) NOT NULL,
            "Name" character varying(128) NOT NULL,
            "Description" character varying(500) NOT NULL DEFAULT '',
            "Days" integer NOT NULL DEFAULT 0,
            "AdvancePercentage" numeric(5,2) NOT NULL DEFAULT 0,
            "IsActive" boolean NOT NULL DEFAULT true
        );

        CREATE UNIQUE INDEX "IX_vendor_payment_terms_Code" ON vendor_payment_terms ("Code");
    END IF;

    -- 3. Vendors Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendors'
    ) THEN
        CREATE TABLE vendors (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VendorCode" character varying(64) NOT NULL,
            "Name" character varying(256) NOT NULL,
            "LegalName" character varying(256) NOT NULL DEFAULT '',
            "DisplayName" character varying(256) NOT NULL DEFAULT '',
            "GSTIN" character varying(32) NOT NULL DEFAULT '',
            "PAN" character varying(32) NOT NULL DEFAULT '',
            "TaxIdentificationNumber" character varying(64) NOT NULL DEFAULT '',
            "Email" character varying(256) NOT NULL DEFAULT '',
            "Phone" character varying(64) NOT NULL DEFAULT '',
            "AlternatePhone" character varying(64) NOT NULL DEFAULT '',
            "Website" character varying(256) NOT NULL DEFAULT '',
            "PaymentTermId" integer NULL REFERENCES vendor_payment_terms("Id") ON DELETE RESTRICT,
            "CreditLimit" numeric(18,4) NOT NULL DEFAULT 0,
            "Status" character varying(64) NOT NULL DEFAULT 'PendingApproval',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_vendors_VendorCode" ON vendors ("VendorCode");
        CREATE INDEX "IX_vendors_Name" ON vendors ("Name");
        CREATE INDEX "IX_vendors_GSTIN" ON vendors ("GSTIN");
        CREATE INDEX "IX_vendors_PAN" ON vendors ("PAN");
        CREATE INDEX "IX_vendors_Status" ON vendors ("Status");
    END IF;

    -- 4. Vendor Contacts Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_contacts'
    ) THEN
        CREATE TABLE vendor_contacts (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VendorId" integer NOT NULL REFERENCES vendors("Id") ON DELETE CASCADE,
            "FirstName" character varying(128) NOT NULL,
            "LastName" character varying(128) NOT NULL DEFAULT '',
            "Designation" character varying(128) NOT NULL DEFAULT '',
            "Email" character varying(256) NOT NULL DEFAULT '',
            "Phone" character varying(64) NOT NULL DEFAULT '',
            "AlternatePhone" character varying(64) NOT NULL DEFAULT '',
            "IsPrimary" boolean NOT NULL DEFAULT false,
            "IsActive" boolean NOT NULL DEFAULT true
        );

        CREATE INDEX "IX_vendor_contacts_VendorId" ON vendor_contacts ("VendorId");
    END IF;

    -- 5. Vendor Addresses Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_addresses'
    ) THEN
        CREATE TABLE vendor_addresses (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VendorId" integer NOT NULL REFERENCES vendors("Id") ON DELETE CASCADE,
            "AddressType" character varying(64) NOT NULL DEFAULT 'Billing',
            "AddressLine1" character varying(256) NOT NULL,
            "AddressLine2" character varying(256) NOT NULL DEFAULT '',
            "City" character varying(128) NOT NULL DEFAULT '',
            "State" character varying(128) NOT NULL DEFAULT '',
            "PostalCode" character varying(32) NOT NULL DEFAULT '',
            "Country" character varying(128) NOT NULL DEFAULT 'India',
            "IsPrimary" boolean NOT NULL DEFAULT false,
            "IsActive" boolean NOT NULL DEFAULT true
        );

        CREATE INDEX "IX_vendor_addresses_VendorId" ON vendor_addresses ("VendorId");
    END IF;

    -- 6. Vendor Compliances Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_compliances'
    ) THEN
        CREATE TABLE vendor_compliances (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VendorId" integer NOT NULL REFERENCES vendors("Id") ON DELETE CASCADE,
            "GSTIN" character varying(32) NOT NULL DEFAULT '',
            "PAN" character varying(32) NOT NULL DEFAULT '',
            "TaxIdentificationNumber" character varying(64) NOT NULL DEFAULT '',
            "GSTRegistered" boolean NOT NULL DEFAULT false,
            "MSMERegistered" boolean NOT NULL DEFAULT false,
            "MSMENumber" character varying(64) NOT NULL DEFAULT '',
            "CertificateNumber" character varying(128) NOT NULL DEFAULT '',
            "CertificateExpiryDate" timestamp with time zone NULL,
            "ComplianceStatus" character varying(64) NOT NULL DEFAULT 'PendingVerification',
            "Remarks" character varying(1000) NOT NULL DEFAULT ''
        );

        CREATE UNIQUE INDEX "IX_vendor_compliances_VendorId" ON vendor_compliances ("VendorId");
    END IF;

    -- 7. Vendor Status Histories Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'vendor_status_histories'
    ) THEN
        CREATE TABLE vendor_status_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VendorId" integer NOT NULL REFERENCES vendors("Id") ON DELETE CASCADE,
            "Status" character varying(64) NOT NULL,
            "PreviousStatus" character varying(64) NULL,
            "User" character varying(256) NOT NULL DEFAULT '',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Date" timestamp with time zone NOT NULL DEFAULT NOW()
        );

        CREATE INDEX "IX_vendor_status_histories_VendorId_Date" ON vendor_status_histories ("VendorId", "Date");
    END IF;

END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "vendor_status_histories");
            migrationBuilder.DropTable(name: "vendor_compliances");
            migrationBuilder.DropTable(name: "vendor_addresses");
            migrationBuilder.DropTable(name: "vendor_contacts");
            migrationBuilder.DropTable(name: "vendors");
            migrationBuilder.DropTable(name: "vendor_payment_terms");
            migrationBuilder.DropTable(name: "vendor_document_sequences");
        }
    }
}
