using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260827000000_AddProcurementPhase5GoodsReceipts")]
    public partial class AddProcurementPhase5GoodsReceipts : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    -- 1. Document Sequence
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'goods_receipt_document_sequences'
    ) THEN
        CREATE TABLE goods_receipt_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Prefix" character varying(64) NOT NULL,
            "LastSequence" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_goods_receipt_document_sequences_Prefix" ON goods_receipt_document_sequences ("Prefix");
    END IF;

    -- 2. Goods Receipts Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'goods_receipts'
    ) THEN
        CREATE TABLE goods_receipts (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "GRNNumber" character varying(64) NOT NULL,
            "PurchaseOrderId" integer NOT NULL REFERENCES purchase_orders("Id") ON DELETE RESTRICT,
            "PurchaseOrderNumber" character varying(64) NOT NULL,
            "VendorName" character varying(256) NOT NULL,
            "ReceiptDate" timestamp with time zone NOT NULL,
            "Warehouse" character varying(256) NOT NULL DEFAULT 'Main Store — Sanand',
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_goods_receipts_GRNNumber" ON goods_receipts ("GRNNumber");
        CREATE INDEX "IX_goods_receipts_Status" ON goods_receipts ("Status");
        CREATE INDEX "IX_goods_receipts_PurchaseOrderId" ON goods_receipts ("PurchaseOrderId");
    END IF;

    -- 3. Goods Receipt Items Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'goods_receipt_items'
    ) THEN
        CREATE TABLE goods_receipt_items (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "GoodsReceiptId" integer NOT NULL REFERENCES goods_receipts("Id") ON DELETE CASCADE,
            "PurchaseOrderLineId" integer NOT NULL,
            "ItemName" character varying(256) NOT NULL,
            "Description" character varying(1000) NOT NULL DEFAULT '',
            "Unit" character varying(64) NOT NULL DEFAULT 'Nos',
            "OrderedQuantity" numeric(18,4) NOT NULL,
            "PreviouslyReceivedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "RemainingQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "ReceivedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "RejectedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "Remarks" character varying(2000) NOT NULL DEFAULT ''
        );

        CREATE INDEX "IX_goods_receipt_items_GoodsReceiptId" ON goods_receipt_items ("GoodsReceiptId");
        CREATE INDEX "IX_goods_receipt_items_PurchaseOrderLineId" ON goods_receipt_items ("PurchaseOrderLineId");
    END IF;

    -- 4. Goods Receipt Status Histories Table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'goods_receipt_status_histories'
    ) THEN
        CREATE TABLE goods_receipt_status_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "GoodsReceiptId" integer NOT NULL REFERENCES goods_receipts("Id") ON DELETE CASCADE,
            "Status" character varying(64) NOT NULL,
            "PreviousStatus" character varying(64) NULL,
            "Date" timestamp with time zone NOT NULL DEFAULT NOW(),
            "User" character varying(256) NOT NULL DEFAULT '',
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Label" character varying(256) NOT NULL DEFAULT ''
        );

        CREATE INDEX "IX_goods_receipt_status_histories_GoodsReceiptId_Date" ON goods_receipt_status_histories ("GoodsReceiptId", "Date");
    END IF;

END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "goods_receipt_status_histories");
            migrationBuilder.DropTable(name: "goods_receipt_items");
            migrationBuilder.DropTable(name: "goods_receipts");
            migrationBuilder.DropTable(name: "goods_receipt_document_sequences");
        }
    }
}
