using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddSalesTargets : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'sales_target_document_sequences'
    ) THEN
        CREATE TABLE sales_target_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "FinancialYear" integer NOT NULL,
            "Prefix" character varying(16) NOT NULL,
            "LastNumber" integer NOT NULL,
            "CreatedOn" timestamp with time zone NOT NULL
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public'
          AND indexname = 'IX_sales_target_document_sequences_FinancialYear_Prefix'
    ) THEN
        CREATE UNIQUE INDEX "IX_sales_target_document_sequences_FinancialYear_Prefix"
            ON sales_target_document_sequences ("FinancialYear", "Prefix");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'sales_targets'
    ) THEN
        CREATE TABLE sales_targets (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "TargetNumber" character varying(64) NOT NULL,
            "TargetName" character varying(256) NOT NULL,
            "TargetType" character varying(64) NOT NULL,
            "TargetCategory" character varying(64) NOT NULL,
            "AssignmentType" character varying(64) NOT NULL,
            "SalesPersonUserId" integer NULL,
            "SalesTeam" character varying(128) NOT NULL,
            "Branch" character varying(128) NOT NULL,
            "RegionalManager" character varying(128) NOT NULL,
            "FinancialYear" integer NOT NULL,
            "StartDate" date NOT NULL,
            "EndDate" date NOT NULL,
            "TargetValue" numeric(18,2) NOT NULL,
            "AchievedValue" numeric(18,2) NOT NULL,
            "RemainingValue" numeric(18,2) NOT NULL,
            "AchievementPercentage" numeric(9,2) NOT NULL,
            "Currency" character varying(8) NOT NULL,
            "Status" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL,
            "CreatedBy" character varying(64) NOT NULL,
            "CreatedDate" timestamp with time zone NOT NULL,
            "UpdatedBy" character varying(64) NOT NULL,
            "UpdatedDate" timestamp with time zone NOT NULL,
            "IsDeleted" boolean NOT NULL DEFAULT FALSE
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_sales_targets_TargetNumber') THEN
        CREATE UNIQUE INDEX "IX_sales_targets_TargetNumber" ON sales_targets ("TargetNumber");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_sales_targets_Status') THEN
        CREATE INDEX "IX_sales_targets_Status" ON sales_targets ("Status");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_sales_targets_TargetCategory') THEN
        CREATE INDEX "IX_sales_targets_TargetCategory" ON sales_targets ("TargetCategory");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_sales_targets_SalesPersonUserId') THEN
        CREATE INDEX "IX_sales_targets_SalesPersonUserId" ON sales_targets ("SalesPersonUserId");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_sales_targets_FinancialYear') THEN
        CREATE INDEX "IX_sales_targets_FinancialYear" ON sales_targets ("FinancialYear");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_sales_targets_StartDate') THEN
        CREATE INDEX "IX_sales_targets_StartDate" ON sales_targets ("StartDate");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_sales_targets_EndDate') THEN
        CREATE INDEX "IX_sales_targets_EndDate" ON sales_targets ("EndDate");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_sales_targets_IsDeleted') THEN
        CREATE INDEX "IX_sales_targets_IsDeleted" ON sales_targets ("IsDeleted");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'sales_target_assignments'
    ) THEN
        CREATE TABLE sales_target_assignments (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "SalesTargetId" integer NOT NULL,
            "SalesPersonUserId" integer NOT NULL,
            "AssignedTarget" numeric(18,2) NOT NULL,
            "AchievedValue" numeric(18,2) NOT NULL,
            "AchievementPercentage" numeric(9,2) NOT NULL,
            "Status" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL,
            "AssignedBy" character varying(64) NOT NULL,
            "AssignedDate" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_sales_target_assignments_sales_targets_SalesTargetId"
                FOREIGN KEY ("SalesTargetId") REFERENCES sales_targets ("Id") ON DELETE CASCADE
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE indexname = 'IX_sales_target_assignments_SalesTargetId_SalesPersonUserId'
    ) THEN
        CREATE INDEX "IX_sales_target_assignments_SalesTargetId_SalesPersonUserId"
            ON sales_target_assignments ("SalesTargetId", "SalesPersonUserId");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_sales_target_assignments_SalesPersonUserId') THEN
        CREATE INDEX "IX_sales_target_assignments_SalesPersonUserId"
            ON sales_target_assignments ("SalesPersonUserId");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'sales_target_progress_histories'
    ) THEN
        CREATE TABLE sales_target_progress_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "SalesTargetId" integer NOT NULL,
            "OldAchievedValue" numeric(18,2) NOT NULL,
            "NewAchievedValue" numeric(18,2) NOT NULL,
            "AchievementPercentage" numeric(9,2) NOT NULL,
            "Action" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL,
            "UpdatedBy" character varying(64) NOT NULL,
            "UpdatedOn" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_sales_target_progress_histories_sales_targets_SalesTargetId"
                FOREIGN KEY ("SalesTargetId") REFERENCES sales_targets ("Id") ON DELETE CASCADE
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE indexname = 'IX_sales_target_progress_histories_SalesTargetId_UpdatedOn'
    ) THEN
        CREATE INDEX "IX_sales_target_progress_histories_SalesTargetId_UpdatedOn"
            ON sales_target_progress_histories ("SalesTargetId", "UpdatedOn");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'sales_target_status_histories'
    ) THEN
        CREATE TABLE sales_target_status_histories (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "SalesTargetId" integer NOT NULL,
            "OldStatus" character varying(64) NULL,
            "NewStatus" character varying(64) NOT NULL,
            "Remarks" character varying(2000) NOT NULL,
            "ChangedBy" character varying(64) NOT NULL,
            "ChangedOn" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_sales_target_status_histories_sales_targets_SalesTargetId"
                FOREIGN KEY ("SalesTargetId") REFERENCES sales_targets ("Id") ON DELETE CASCADE
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE indexname = 'IX_sales_target_status_histories_SalesTargetId_ChangedOn'
    ) THEN
        CREATE INDEX "IX_sales_target_status_histories_SalesTargetId_ChangedOn"
            ON sales_target_status_histories ("SalesTargetId", "ChangedOn");
    END IF;
END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP TABLE IF EXISTS sales_target_status_histories;
DROP TABLE IF EXISTS sales_target_progress_histories;
DROP TABLE IF EXISTS sales_target_assignments;
DROP TABLE IF EXISTS sales_targets;
DROP TABLE IF EXISTS sales_target_document_sequences;
""");
        }
    }
}
