using ERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20260829000000_AddProcurementPhase7InventoryAndStock")]
    public partial class AddProcurementPhase7InventoryAndStock : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    -- 1. Document Sequence
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'store_inventory_document_sequences'
    ) THEN
        CREATE TABLE store_inventory_document_sequences (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Prefix" character varying(64) NOT NULL,
            "LastSequence" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_store_inventory_document_sequences_Prefix" ON store_inventory_document_sequences ("Prefix");
    END IF;

    -- 2. Warehouses
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'warehouses'
    ) THEN
        CREATE TABLE warehouses (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Code" character varying(64) NOT NULL,
            "Name" character varying(256) NOT NULL,
            "Location" character varying(256) NOT NULL DEFAULT '',
            "Address" character varying(500) NOT NULL DEFAULT '',
            "Manager" character varying(256) NOT NULL DEFAULT '',
            "Capacity" numeric(18,4) NOT NULL DEFAULT 0,
            "UsedCapacity" numeric(18,4) NOT NULL DEFAULT 0,
            "AvailableCapacity" numeric(18,4) NOT NULL DEFAULT 0,
            "Status" character varying(64) NOT NULL DEFAULT 'Active',
            "AssignedInventoryCount" integer NOT NULL DEFAULT 0,
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_warehouses_Code" ON warehouses ("Code");
        CREATE INDEX "IX_warehouses_Status" ON warehouses ("Status");
    END IF;

    -- 3. Raw Materials Inventory
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'raw_materials'
    ) THEN
        CREATE TABLE raw_materials (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "MaterialCode" character varying(64) NOT NULL,
            "MaterialName" character varying(256) NOT NULL,
            "Category" character varying(128) NOT NULL DEFAULT '',
            "WarehouseId" integer NOT NULL DEFAULT 0,
            "WarehouseName" character varying(256) NOT NULL DEFAULT '',
            "Rack" character varying(128) NOT NULL DEFAULT '',
            "Unit" character varying(32) NOT NULL DEFAULT 'Nos',
            "OpeningStock" numeric(18,4) NOT NULL DEFAULT 0,
            "AvailableStock" numeric(18,4) NOT NULL DEFAULT 0,
            "ReservedStock" numeric(18,4) NOT NULL DEFAULT 0,
            "MinimumStock" numeric(18,4) NOT NULL DEFAULT 0,
            "MaximumStock" numeric(18,4) NOT NULL DEFAULT 0,
            "ReorderLevel" numeric(18,4) NOT NULL DEFAULT 0,
            "UnitCost" numeric(18,4) NOT NULL DEFAULT 0,
            "CurrentValue" numeric(18,4) NOT NULL DEFAULT 0,
            "BatchCount" integer NOT NULL DEFAULT 0,
            "StockAgeDays" integer NOT NULL DEFAULT 0,
            "StockAgeBand" character varying(64) NOT NULL DEFAULT 'Band0To30',
            "Supplier" character varying(256) NOT NULL DEFAULT '',
            "LastReceiptDate" timestamp with time zone NULL,
            "LinkedGRNId" integer NULL,
            "LinkedGRNNumber" character varying(64) NULL,
            "LinkedPOId" integer NULL,
            "LinkedPONumber" character varying(64) NULL,
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_raw_materials_MaterialCode" ON raw_materials ("MaterialCode");
        CREATE INDEX "IX_raw_materials_WarehouseId" ON raw_materials ("WarehouseId");
        CREATE INDEX "IX_raw_materials_Category" ON raw_materials ("Category");
    END IF;

    -- 4. Finished Goods Inventory
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'finished_goods'
    ) THEN
        CREATE TABLE finished_goods (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProductCode" character varying(64) NOT NULL,
            "ProductName" character varying(256) NOT NULL,
            "FinishedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "ReservedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "AvailableQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "WarehouseId" integer NOT NULL DEFAULT 0,
            "WarehouseName" character varying(256) NOT NULL DEFAULT '',
            "BatchNumber" character varying(128) NOT NULL DEFAULT '',
            "ProductionReference" character varying(128) NOT NULL DEFAULT '',
            "ManufacturingDate" timestamp with time zone NOT NULL DEFAULT NOW(),
            "ExpiryDate" timestamp with time zone NULL,
            "UnitCost" numeric(18,4) NOT NULL DEFAULT 0,
            "CurrentValue" numeric(18,4) NOT NULL DEFAULT 0,
            "DispatchStatus" character varying(64) NOT NULL DEFAULT 'NotReady',
            "Unit" character varying(32) NOT NULL DEFAULT 'Nos',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_finished_goods_ProductCode" ON finished_goods ("ProductCode");
        CREATE INDEX "IX_finished_goods_WarehouseId" ON finished_goods ("WarehouseId");
    END IF;

    -- 5. Stock Transactions
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'stock_transactions'
    ) THEN
        CREATE TABLE stock_transactions (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "TransactionNumber" character varying(64) NOT NULL,
            "TransactionType" character varying(64) NOT NULL DEFAULT 'StockIn',
            "MaterialId" integer NULL,
            "MaterialCode" character varying(64) NOT NULL DEFAULT '',
            "MaterialName" character varying(256) NOT NULL DEFAULT '',
            "WarehouseId" integer NOT NULL DEFAULT 0,
            "WarehouseName" character varying(256) NOT NULL DEFAULT '',
            "Quantity" numeric(18,4) NOT NULL DEFAULT 0,
            "Unit" character varying(32) NOT NULL DEFAULT 'Nos',
            "Reason" character varying(256) NOT NULL DEFAULT '',
            "ReferenceType" character varying(64) NOT NULL DEFAULT 'None',
            "ReferenceNumber" character varying(64) NOT NULL DEFAULT '',
            "ReferenceId" integer NULL,
            "User" character varying(256) NOT NULL DEFAULT '',
            "TransactionDate" timestamp with time zone NOT NULL DEFAULT NOW(),
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_stock_transactions_TransactionNumber" ON stock_transactions ("TransactionNumber");
        CREATE INDEX "IX_stock_transactions_TransactionType" ON stock_transactions ("TransactionType");
        CREATE INDEX "IX_stock_transactions_WarehouseId" ON stock_transactions ("WarehouseId");
        CREATE INDEX "IX_stock_transactions_MaterialId" ON stock_transactions ("MaterialId");
    END IF;

    -- 6. Inventory Batches
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'inventory_batches'
    ) THEN
        CREATE TABLE inventory_batches (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "BatchNumber" character varying(128) NOT NULL,
            "MaterialId" integer NOT NULL DEFAULT 0,
            "MaterialCode" character varying(64) NOT NULL DEFAULT '',
            "MaterialName" character varying(256) NOT NULL DEFAULT '',
            "WarehouseId" integer NOT NULL DEFAULT 0,
            "WarehouseName" character varying(256) NOT NULL DEFAULT '',
            "Supplier" character varying(256) NOT NULL DEFAULT '',
            "GRNId" integer NULL,
            "GRNNumber" character varying(64) NULL,
            "ManufacturingDate" timestamp with time zone NOT NULL DEFAULT NOW(),
            "ExpiryDate" timestamp with time zone NULL,
            "AvailableQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "ConsumedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "RemainingQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "Unit" character varying(32) NOT NULL DEFAULT 'Nos',
            "UnitCost" numeric(18,4) NOT NULL DEFAULT 0,
            "Status" character varying(64) NOT NULL DEFAULT 'Active',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE INDEX "IX_inventory_batches_BatchNumber" ON inventory_batches ("BatchNumber");
        CREATE INDEX "IX_inventory_batches_Status" ON inventory_batches ("Status");
        CREATE INDEX "IX_inventory_batches_MaterialId" ON inventory_batches ("MaterialId");
    END IF;

    -- 7. Stock Transfers
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'stock_transfers'
    ) THEN
        CREATE TABLE stock_transfers (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "TransferNumber" character varying(64) NOT NULL,
            "FromWarehouseId" integer NOT NULL DEFAULT 0,
            "FromWarehouseName" character varying(256) NOT NULL DEFAULT '',
            "ToWarehouseId" integer NOT NULL DEFAULT 0,
            "ToWarehouseName" character varying(256) NOT NULL DEFAULT '',
            "TotalQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "Status" character varying(64) NOT NULL DEFAULT 'Draft',
            "TransferDate" timestamp with time zone NOT NULL DEFAULT NOW(),
            "RequestedBy" character varying(256) NOT NULL DEFAULT '',
            "ApprovedBy" character varying(256) NULL,
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_stock_transfers_TransferNumber" ON stock_transfers ("TransferNumber");
        CREATE INDEX "IX_stock_transfers_Status" ON stock_transfers ("Status");
    END IF;

    -- 8. Stock Transfer Items
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'stock_transfer_items'
    ) THEN
        CREATE TABLE stock_transfer_items (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "StockTransferId" integer NOT NULL REFERENCES stock_transfers("Id") ON DELETE CASCADE,
            "MaterialId" integer NOT NULL DEFAULT 0,
            "MaterialCode" character varying(64) NOT NULL DEFAULT '',
            "MaterialName" character varying(256) NOT NULL DEFAULT '',
            "Unit" character varying(32) NOT NULL DEFAULT 'Nos',
            "Quantity" numeric(18,4) NOT NULL DEFAULT 0,
            "BatchNumber" character varying(128) NULL
        );

        CREATE INDEX "IX_stock_transfer_items_StockTransferId" ON stock_transfer_items ("StockTransferId");
    END IF;

    -- 9. Stock Alerts
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'stock_alerts'
    ) THEN
        CREATE TABLE stock_alerts (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "MaterialId" integer NOT NULL DEFAULT 0,
            "MaterialCode" character varying(64) NOT NULL DEFAULT '',
            "MaterialName" character varying(256) NOT NULL DEFAULT '',
            "WarehouseId" integer NOT NULL DEFAULT 0,
            "WarehouseName" character varying(256) NOT NULL DEFAULT '',
            "CurrentStock" numeric(18,4) NOT NULL DEFAULT 0,
            "MinimumStock" numeric(18,4) NOT NULL DEFAULT 0,
            "ReorderQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "Unit" character varying(32) NOT NULL DEFAULT 'Nos',
            "Priority" character varying(64) NOT NULL DEFAULT 'Warning',
            "SuggestedPurchase" boolean NOT NULL DEFAULT true,
            "LinkedRequisitionId" integer NULL,
            "LinkedRequisitionNumber" character varying(64) NULL,
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
        );

        CREATE INDEX "IX_stock_alerts_Priority" ON stock_alerts ("Priority");
        CREATE INDEX "IX_stock_alerts_MaterialId" ON stock_alerts ("MaterialId");
    END IF;

    -- 10. Physical Verifications
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'physical_verifications'
    ) THEN
        CREATE TABLE physical_verifications (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VerificationNumber" character varying(64) NOT NULL,
            "WarehouseId" integer NOT NULL DEFAULT 0,
            "WarehouseName" character varying(256) NOT NULL DEFAULT '',
            "Verifier" character varying(256) NOT NULL DEFAULT '',
            "VerificationDate" timestamp with time zone NOT NULL DEFAULT NOW(),
            "ExpectedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "ActualQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "Variance" numeric(18,4) NOT NULL DEFAULT 0,
            "VarianceValue" numeric(18,4) NOT NULL DEFAULT 0,
            "Status" character varying(64) NOT NULL DEFAULT 'Scheduled',
            "AdjustmentPosted" boolean NOT NULL DEFAULT false,
            "Remarks" character varying(2000) NOT NULL DEFAULT '',
            "Notes" character varying(2000) NOT NULL DEFAULT '',
            "ApprovedBy" character varying(256) NULL,
            "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "CreatedBy" character varying(256) NOT NULL DEFAULT '',
            "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
            "UpdatedBy" character varying(256) NOT NULL DEFAULT '',
            "IsDeleted" boolean NOT NULL DEFAULT false
        );

        CREATE UNIQUE INDEX "IX_physical_verifications_VerificationNumber" ON physical_verifications ("VerificationNumber");
        CREATE INDEX "IX_physical_verifications_Status" ON physical_verifications ("Status");
    END IF;

    -- 11. Physical Verification Lines
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'physical_verification_lines'
    ) THEN
        CREATE TABLE physical_verification_lines (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PhysicalVerificationId" integer NOT NULL REFERENCES physical_verifications("Id") ON DELETE CASCADE,
            "MaterialId" integer NOT NULL DEFAULT 0,
            "MaterialCode" character varying(64) NOT NULL DEFAULT '',
            "MaterialName" character varying(256) NOT NULL DEFAULT '',
            "Unit" character varying(32) NOT NULL DEFAULT 'Nos',
            "ExpectedQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "ActualQuantity" numeric(18,4) NOT NULL DEFAULT 0,
            "Variance" numeric(18,4) NOT NULL DEFAULT 0,
            "Remarks" character varying(2000) NOT NULL DEFAULT ''
        );

        CREATE INDEX "IX_physical_verification_lines_PhysicalVerificationId" ON physical_verification_lines ("PhysicalVerificationId");
    END IF;

END $$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "physical_verification_lines");
            migrationBuilder.DropTable(name: "physical_verifications");
            migrationBuilder.DropTable(name: "stock_alerts");
            migrationBuilder.DropTable(name: "stock_transfer_items");
            migrationBuilder.DropTable(name: "stock_transfers");
            migrationBuilder.DropTable(name: "inventory_batches");
            migrationBuilder.DropTable(name: "stock_transactions");
            migrationBuilder.DropTable(name: "finished_goods");
            migrationBuilder.DropTable(name: "raw_materials");
            migrationBuilder.DropTable(name: "warehouses");
            migrationBuilder.DropTable(name: "store_inventory_document_sequences");
        }
    }
}
