using CRM.DATA;
using Microsoft.EntityFrameworkCore;

namespace CRM.Helpers
{
    /// <summary>
    /// Ensures the DataProtectionKeys table exists in PostgreSQL for persistent ASP.NET Core Data Protection keys.
    /// </summary>
    public static class DataProtectionKeysSchemaEnsure
    {
        public static async Task EnsureAsync(
            TaskDbcontext db,
            ILogger logger,
            CancellationToken cancellationToken = default)
        {
            try
            {
                await db.Database.ExecuteSqlRawAsync(
                    """
                    CREATE TABLE IF NOT EXISTS "DataProtectionKeys" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "FriendlyName" text NULL,
                        "Xml" text NULL
                    );
                    """,
                    cancellationToken);
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "DataProtectionKeys table schema ensure failed or skipped.");
            }
        }
    }
}
